### ISSUE TITLE
[bug] - Legacy user login bug

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1027]
**Describe the bug**
As discussed on slack (https://onearmy.slack.com/archives/CHUDUK0UV/p1599150097000600?thread_ts=1599062533.001400&cid=CHUDUK0UV)

There are still some older accounts that have incorrect auth information and should be migrated.  It would be worth going through sentry messages to see how many different users there are (around 180 events recorded, but lots of duplicates), and then see which can be addressed. 

Current work around code in `src/stores.user.store.ts` can also be tidied once resolved
![image](https://user-images.githubusercontent.com/10515065/92141814-d1104280-edc7-11ea-95e5-4489bd1b106f.png)

**To Reproduce**
Only via specific users who don't have the correct `authID` specified, so hard to reproduce. 

**Screenshots**
(see slack thread)

**Comment by ivokh** [comment]
I took a quick look at this and it seems like the getUserProfile is used for different purposes.
It's used by the sign-in logic to get the meta data of an authorized user. For this purpose only the _authID should be used but that's not possible because of the older accounts.
It's also used to get the user metadata for map pins and the user page. For this purpose it should only use the _id property. I think that's possible also without modifying the old accounts.
I would suggest to create two functions: getUserProfileBy(Username or Id) and getUserProfileBy(UID or AuthID) to differentiate the different uses.

Then I think it would be possible to modify all the old accounts (It looks like they have no _authID property) by adding a _authID property and setting its value to the _id value.
Than the only problem is that the old accounts have a uid as the _id instead of a username. I'm not sure if that is a real problem but to make a fix for that in the future easier it might be a good idea to mark the old accounts during the modification.

I have no experience with writing a function to do the modifications on the database but I would like to look into that. I mean I have no experience with firebase/firestore. What would be the best approach to test/debug such a function?

Is there a way to give me access to the slack thread?

**Comment by iSCJT** [comment]
Closing as issues with users handled as part of other pr's.
