### ISSUE TITLE
[feature request] display "my pin" btn for notlogged in user

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#1048]
[As discussed](https://github.com/ONEARMY/community-platform/pull/1035#issuecomment-692021318) in #1035 display map pin button also for not logged in user.

**Comment by markjbuss** [comment]
Looks like this was fixed as part of https://github.com/ONEARMY/community-platform/commit/7726a684af050afd77c1ef9497b7f256b2bbdd89 ?

**Comment by BenGamma** [comment]
Good catch, it's a first try of fixing the issue.
It display the link to settings for not logged in users, in pretty much the same way as in events and how-to.
For some reasons the link doesn't work yet.
I think it is due to the dynamic handling of the url routing in the map, but it will require more investigations.

Feel free if you want to have a look :)

**Comment by chrismclarke** [comment]
The issue is that map clicks also trigger navigation, so the user is first directed to /settings and then straight back to /map. I'm not exactly sure why this is, but a better solution would be to use `event.stopPropagation()` on the button click handler. I'll add this to the open pr.

The other question I would be wondering is whether the my-pin button should focus in on the user's pin on the map (if they have one) instead, and only go to settings if they don't have one. But this might be more work than wanted right now.
