### ISSUE TITLE
[feature request] Portrait images in how-to landscape

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1054]
**Problem**
Portrait images are displayed in original ratio in how-to. This makes formatting weird. 

**Describe the solution you'd like**
All images (square, portrait, landscape etc) should be displayed in the same ratio. Just like we do with the little thumbnails underneat. You can click the image to see the original ratio/size.

**Example**
Here you can see a screenshot of how it is now and how it should be
![crop-image](https://user-images.githubusercontent.com/13672737/94998517-8cd4b580-05b2-11eb-9d76-d7b13e656c4d.jpg)

**Comment by markjbuss** [comment]
I can't reproduce this with portrait images, Looks like they are being cropped as suggested on my local.

**Comment by davehakkens** [comment]
you might be right. sometimes it shows good. This is how I see it in (incognito) Firefox 
<img width="1270" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/95071747-717cbe00-070a-11eb-964a-85340f2dbfe0.png">

This is in Chrome (correct)
<img width="1257" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/95071791-80637080-070a-11eb-863e-7bbe0ddc2b5f.png">

**Comment by markjbuss** [comment]
Ah yeah, other browsers are a thing 😆 I have repro'd locally with firefox now. Will see if I can figure out what's wrong.

**Comment by markjbuss** [comment]
Can't see anything obvious here, have googled a bit around object-fit not working in firefox but nothing relevant here. Will leave this for somebody with far superior front end skills than myself 🙇

**Comment by tudi2d** [comment]
@markjbuss Thanks for creating a how-to on dev. Made it much easier to reproduce again! :) This bug is related to how Chrome and Firefox calculate the width of elements. By default both browser use `width: auto` for an element, when the width is not explicitly defined. When the element uses `display: flex` Chrome calculates the width of the flex items while Firefox is not doing so. This is why it looked as intended in Chrome. I fixed it by replacing the flex wrapper with a Box component using `display: block`. `display: flex` is not necessary here, because the wrapper always contains only one element. In general it is better to use `display: flex` only when necessary.

**Comment by BenGamma** [comment]
Thanks @tudi2d 
I guess we were using a flex box here because it used to hold more elements, but didn't changed when removed them.
Good catch 🙆‍♂️
