### ISSUE TITLE
Alternative content structures & sources

### ISSUE THREAD

**Issue by catx23** [ONEARMY/community-platform#1090]
Hi,

is there any chance to dump pre-compiled HTML content as howto ? 

As much I'd like but the current structure won't allow us to publish meaningful/compelling content. We're in machining and related trades and simple tasks can be often a can of flies - even for professionals. It takes a quite often more than just 400 words - or 3 pictures, accompanied by lots of links/references. 

This way I can also use snippets for repetitive or common subjects or tasks, shared in multiple howtos. In example, doing a howto for the arbor injector or the bench extruder would end-up in an awful mess - easily 50+ steps. I'd prefer to communicate/document rather the keys and background for certain tasks.

I could add this feature as PR myself, in a way others can use their preferred editor, paving the way for rich articles as well. 

thanks

btw. I'd suggest to switch also here to Jekyll and use the current code only for editing - for numerous and important reasons. I imported the howtos as well : https://github.com/plastic-hub/pp-next/blob/master/_howtos/contribute-to-open-source-projects.md. This is going to be in a library, made with Jekyll around as well.

**Comment by chrismclarke** [comment]
At this stage I don't think that would be possible, everything is set up for rendering content from the specific format as produced from the input forms. The best compromise I could think of would be to try and create an API endpoint that would accept a post request for a howto, and then leave it to others to find a way to convert their local content into the right format for the request - I'm not sure what your thoughts on that might be? I think uniformity/consistent is something the PP team is strongly going for with the howtos, so the API would likely also strip out any html.

Otherwise, we've just started work on a new 'Research' module that will likely have less structured content, maybe we could also support HTML content there instead (I remember at one point we did have various wysiwyg editors and HTML floating around). I think the original reason however why we opted away from HTML, markdown and content in git was to make it possible for people with minimal dev experience to contribute more easily, but now that we have those mechanisms mostly in place I see no reason we shouldn't start pushing in more directions also. 

The big question I always have is whether we start trying to do these things incrementally, or commit to a giant overhaul (personally I'd love to see a v2 backed onto either postgres or mongo, graphql compatible, decent rest API and running on docker... but for that I think we'd need to find a way of getting a whole new dev team together and some stronger financial backing/sustainability models).

I'm just starting to try and step back into the project after quite a break, still not sure how much time I'll be able to find but really awesome to see there's still people interested in helping push this project forward!

**Comment by catx23** [comment]
Alright I see.

We think the PP team isn't really aware about daily user needs or really familiar about the trade the community is dealing with. A little pity it's being treated more as a design pet project though. Being in plastic recycling, machining and end-user wise is a matter of highly technical details to be referenced and authored. You can call it science. We need tables, markdown, equations and some freedom to structure content our-self. Of course for trivial tasks the system as now could be enough to describe some basic steps as gluing some stuff together. We found it already very sad to have no publishing of blogs, articles as we had in the forum. The project's is actual progress is basically depending on this authoring tools - now we see it rather degrading because of those things. 

However, by being not able to author the content as others and my self need it, we lock out pretty much out more skilled folks. The other day Dave was even about banning me for mentioning or recommending to learn Markdown. There are also quite some power users who'd like to add content - in a way it deserves. 

It's just a matter of tweaking the interface for basic option toggles : 1. HTML, 2. Markdown, 3. Basic. So every user type can be served - just as you'd have in popular platforms (WP, and even in the bazar). That means that the current 'document' should be extended for an universal 'meta' field (key-value store) to determine the rendering.

Yes, I 've seen your research module. Not sure what to think about but from what I see there are actually a number of document types (or presets) : Howto, Article/Blog, Research to be treated individually. 

Anyway, for what we need to publish on this platform (among others: wikifactory, hackaday, libary, manuals...), we just need the mentioned toggle 'raw' to dump some HTML. That's easy for me to add but also render it as just. In this case, I'd of course apply some basic structures to guarantee a sort of uniformity. Also adding a button for 'edit' (on github or alternative editors) is pretty simple - others have it easy to contribute or improve the article.    
 
About adding an API, yes - I investigated this also in this regard but doesn't seem that easy. There isn't a good NodeJS API for CLI languages as far I've seen. I've been so far very happy with Jekyll and file based content, easy to tweak and edit. No dependencies or heavy JS stuff - at least when it's about content. But would be cool to add or refresh content this way. If you have ideas, let me know. CLI based would be great - I am even fine with Puppeteer scripts :-)

All this pain btw. could be all solved with going for a modded Discourse of course :-) It's all in there, ACL, rich text, ... name it, even RT communication, ...

cheers, nice to see you back. If there is financial support needed - for things we consider urgent or beneficial, I am all open.

g

**Comment by catx23** [comment]
![image](https://user-images.githubusercontent.com/1205100/106283867-bccf5500-6242-11eb-99db-b2c5689f9282.png)

Here some examples. Writing an article about how to make such parts, machines or systems is rather an educational task. It isn't done with a 1-2-3 tutorial. At many points you have to explain also about alternative ways doing it and what's actuallu important, also due to local stock size limitations. Making the bearing housing or the motor flange in the picture for instance deserves alone a whole page. At some point I'd love also include tables about ISO fits & tolerances, among other things such as gearbox types, etc... 

just saying :-)

**Comment by chrismclarke** [comment]
I feel another thing the platform is missing, based on what you describe, is a better way so that more people can author things in a style like the academy section - i.e. multiple content pages linked together. The current academy page is actually just an iframe of another repo where all the content is written in markdown and rendered via docusaurus (similar to jekyll/gatsby, being pushed by the core facebook/react team, nothing too special but gets the job done)

I floated the idea of turning the academy more into a module so that people can author their own sets of connected content and there seemed to be some interest at least, but I don't expect it to happen any time soon (dev is still limited to just 1-2 very part-time people at the moment). Shorter term people said they'd be happy if we plan to include markdown input in the research module, so that could be good option too. If we at least have the structures in place for editing/displaying richer text then adding an API could follow a bit more naturally (I really like swagger as an API tooling system, which you would likely partner with an express-js or nest-js server). 

As for content editors - I remember at one time we had draft.js in the platform and I think someone else also investigated tinymce, although not sure what tends to be the most popular these days for either HTML or markdown... I'm not sure if you have any thoughts?

**Comment by catx23** [comment]
Hey,
just saw your message. 

Good to hear there is interest in Markdown :-)

I wouldn't push to much on a complete CMS - far from doable with the new tech around given the manpower. I was about to recommend using a traditional CMS just - has most on board so far. Instead, I think it might be enough content to pull Github repos just and display it some sort of directory. I've seen this quite often actually for more advanced projects. This way you won't need to write all the stuff as editor, etc...

But if it's about adding an editor at least for the basic crowd. Yes, TinyMCE might be still the best choice - it feels complete - not as the sluggish new react stuff :-). Otherwise, I'd and will opt for Monaco, the editor which powers VSCode.

Yes, swagger is really neat, I used it a few times together with nest-js - sort of Angular - just for the server. Comes out all clean and easy to mod but still - not sure you guys can deal with managing/maintaining a full stack though. I'd again look for something existing and small.

Anyway, evtl. you could adjust the research module, make it a bit more generic (articles) - add a proper editor but more importantly - enable pulling content from repos and display it in some tree or whatever fits. May worth the risk - I am usually in good faith that educating folks pays out at the end :-)   

As for my part I am focusing now to add some widgets to Jekyll (file grid view) but also an editor with some template/macro aids. Docusaurus has no template language btw. - the reason I'd drop it. At some point authors will need snippets or configurable templates - using this in Jekyll everywhere :-)

**Comment by catx23** [comment]
There are btw. also a few good web IDEs - can't remember the names. But Cloud9 comes to mind and there a few projects which brought VSCode to the web. With some luck you can mod these just for a sort of Git VFS (have one) and some basic ACL (have one as well). 

At the end you may want just some basic system - maintained by others but you extend it using their Plugin interface (custom tags, ...).

Going that path looks more reasonable to me. Ideally folks mount their projects, articles from remote locations for instance.
