### ISSUE TITLE
Research module live, but only for specific users

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1118]
### Description

The research module that is being developed here https://github.com/ONEARMY/community-platform/pull/1116 should go on the live site. However it shouldn't be public available since we first want to do some proper testing. It would be good if we can "invite" a few users to use the tool for beta testing. 

 I could see it something as basic as having a field in firebase backend for users that we manually assign:
 `beta tester: yes` (shows the module.)
This would also be useful in the future when we release new features. But not sure what is the best way to implement.

### Page related

Will be used in :
https://dev.onearmy.world/research

**Comment by chrismclarke** [comment]
Makes sense to me, from the technical side I think we might want to clarify our approach to levels of user permission/roles. What we have currently:

- 2 custom user roles which are `admin` and `super-admin` (which go beyond standard logged-in/anonymous)
- A minimal dashboard where admins can be added (super admins only manually in db) 
- Various helper functions to limit specific content to specific roles.

Longer term we will want to define a better system of:

1. Roles - namely what we call them, and whether they are each individual/standalone or if they form a hierarchy so that if you have one particular role you automatically can do things of lower roles (this ideally would be all-or-nothing, the code to say something like 'admins can do everything beta testers can do except...' gets quite messy. Currently roles are stored as an array, so a user can have multiple roles.

2. Permissions - a list of the things it takes specific permissions to do (e.g. view specific module, approve/modify content etc.). At some point this will likely be broken down into specific database operations (e.g. write to howto if not howto owner)

For now, however, I think if someone wanted they can just set to work getting this implemented by copy-pasting code that is used to restrict content via admin privileges for a new `beta_tester` role that would work fine, and then copying the dev pages code to keep a list of pages that only beta testers can see
