### ISSUE TITLE
[feature request] Add a way to check for dead links in how-tos

### ISSUE THREAD

**Issue by darigovresearch** [ONEARMY/community-platform#1167]
**Is your feature request related to a problem? Please describe.**
A user in the discord mentioned one of the how tos had a dead link.

**Describe the solution you'd like**
It would be good if we can have automated checks before publishing & check every week for example to notify the user that they need to make a correction.

**Describe alternatives you've considered**
The time frame for the checks could be daily or monthly depending on how heavy the computation is

**Additional context**
n/a

**Comment by chrismclarke** [comment]
Makes a lot of sense to me that we have some way of notifying/fixing dead links. We're currently developing a comments system to the howtos shortly which might be a good-enough option short term for people to just mention if a link isn't working, instead of relying on automated checks (which could be a bit flaky depending on things like bot-handling, recaptchas etc.).

The other option might be to add a way to notify/flag a howto for issues (e.g. spam, deadlinks etc.), which I think is part of a slightly longer term roadmap, but not sure if it might be overkill adding a button right now next to each link to report dead. 

What's your thoughts @davehakkens ?

**Comment by darigovresearch** [comment]
Another option is just a link crawler that checks it doesn't reach a 404 page which I'm sure that there are also plugins for

**Comment by davehakkens** [comment]
Agree its annoying. 
But indeed I also think comments might already solve some of it, to make sure the makers is even aware of it.
I'd suggest to see how that goes, if we still have many dead links we will take a deeper look at it.

**Comment by chrismclarke** [comment]
OK, for now I'm going to close this issue in the hopes that we can resolve with the comments system, and can revisit in the future if needed.
