### ISSUE TITLE
Add useful to howto

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1174]
### Description

Show the amount of useful for each how-to one the overview page. 
Will also be used with dropdown filter from #1172 

### Page related

Will be used in :
- [How to Overview](https://community.preciousplastic.com/how-to)

### Mockup

![useful](https://user-images.githubusercontent.com/13672737/121788744-9a255380-cbc7-11eb-92c6-098bd7453b74.jpg)

**Comment by chrismclarke** [comment]
So this would actually end up being harder than it looks, due to the way the database is structured and read-optimisations work. Bascially the total votes for a howto is stored inside a sub-collection document of the howto, and by default only read when a user opens the howto. So the naive way to get all totals would be to read all the individual documents every time the page loads, which is a really expensive operation to do (assuming 20k monthly users and 100 or so howtos, this feature alone would probably cost around 2 euro per month in billing costs).

So an alternative method would probably rely on creating a single `stats` or possibly `data_feed` document or similar somewhere, where all the totals are collated and read as a single document (and updated via a cloud function), costing more like 2c per month. Or we try to fast-track the process of moving to a different database setup...

**Comment by davehakkens** [comment]
ah I see the problem. Bummer..
Hope we can find a good way 🤞

**Comment by danitrod** [comment]
@chrismclarke question, couldn't we save the useful stats as a prop in the actual howto docs, so they are loaded together with the other info from howtos?

**Comment by chrismclarke** [comment]
I think we covered this on the call, but just to keep a written record. 

We decided that keeping the info in the individual doc itself would result in too many read updates on the main howto list page (we would need to retrieve all howtos every time the page loads - currently we avoid this by reading once, caching, and only reading again if updated). Instead we can just keep a single document with the stats for all howtos that can be read each time the page is loaded.
