### ISSUE TITLE
Add notifications

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1199]
### Description
After introducing comments we need notifications so users can see they have a message to their content. There will be a small icon in the menubar that shows notifications. We start rolling out notifications in the how-to with two triggers

### 2 Triggers for notifications
**- New comment on a how-to** (if someone posts a comment on a how-to the creator of the how-to receives a notification)
**- New useful on a how-to** (if someone gives a useful to a how-to the creator of the how-to receives a notification) 

# Behaviour

## If there is no notification
- The icon is grey
- On click it says "no notifications"

https://user-images.githubusercontent.com/13672737/127753619-8d7cc8b2-27d5-4723-a480-614ad24e1c2a.mov

## If there are notifications
- The icon changes color.
- New notifications are shown chronologically on date (latest on top)
- The box has a fixed size> if the amount exceeds, scroll
- Notification messages contain URLs to visit the user or how-to
- "Clear notifications" removes all and turns the icon back to grey

https://user-images.githubusercontent.com/13672737/127753685-2636b7e5-1c3a-44ef-aa2d-889dd3f88de9.mov

### Example Live
💻 Live test "no notifications" [here](https://community-platform.webflow.io/u/how-to)
💻 Live test "notifications" [here](https://community-platform.webflow.io/u/how-to-with-notification)

**Comment by chrismclarke** [comment]
Really nice feature to have, we would definitely handle most of this with backend triggered functions so likely will want to add a better testing setup for these before too much work can be done on this. I'll hopefully have that update live at some point this month however, so if anyone does want to take the issue on I'd be more than happy to help support.

**Comment by patrycjapraczyk** [comment]
@chrismclarke could I try to help with this once the testing environment is ready?

**Comment by chrismclarke** [comment]
That would be great! I'm mostly there with the testing environment, just need to find another half day to finish up (hopefully by the end of this week). Will add another message in this thread when ready

**Comment by chrismclarke** [comment]
@patrycjapraczyk - The PR to implement a better system for testing backend functions is now open 🎉 : https://github.com/ONEARMY/community-platform/pull/1207 

Would you be willing to help with testing it at some point over the next week or so? It would be great to have another developer try testing to see if they can also get the emulators working locally and start being able to write their own test functions. This will also be an additional bounty task, because it really helps us make sure the code and instructions are good enough before merging.

The rough steps needed would be:
- Checkout the branch with the emulators code in (`feat/dev-emulators`)
- Run the `yarn install` command to install the updated dependencies
- Try following the instructions added to the documentation (link in the PR)
- Let me know if things work or not, so we can improve the documentation

Let me know if interested, if not or if you're busy then no worries at all, I can ask other people in slack too.

**Comment by patrycjapraczyk** [comment]
Hi there, sorry about the late reply. Sure I could try it out next week,
since this will also be useful when working on the notifications.

**Comment by patrycjapraczyk** [comment]
Hi Luke,

I've made a start on the notifications, I wrote some back-end functions and
also looked at the React components but this is not finished yet and I'm
afraid I won't be able to work on this in the following week.

You can see my progress here:
https://github.com/patrycjapraczyk/community-platform/tree/feat/notifications

Best wishes,
Patrycja

**Comment by davehakkens** [comment]
Hi @patrycjapraczyk how is this going?
As mentioned in the meeting i'm sending the icons. Let me know if you need anything else!
[Icons.zip](https://github.com/ONEARMY/community-platform/files/7719739/Icons.zip)

**Comment by patrycjapraczyk** [comment]
Hey @davehakkens thanks for the icons! Apologies for the delay in responding and working on this.. 
I've just submitted a PR, which adds the notifications feature. I'd appreciate any feedback if the functionality I added matches with what you had in mind. Thanks!
