### ISSUE TITLE
Simplify member profile

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1200]
### Description

Currently, profiles are quite extended, with long descriptions and multiple header images. They are designed for spaces. . With comments coming more individual users (not spaces) will interact. We need a simpler profile with less information for those. This will also be a step towards having "want to get started" pins for members

### Page related

Will be used in member profiles
Example 1 https://community.preciousplastic.com/u/joop
Example 2 https://community.preciousplastic.com/u/disruptivelyuseful

### Mockup Public
![profile(public)](https://user-images.githubusercontent.com/13672737/127755035-2c07a0cb-ee08-464b-be4a-354bdaef0583.jpg)

### Mockup Private (User Input)
![profile(private)](https://user-images.githubusercontent.com/13672737/127754945-719da4b2-f28b-4d22-a097-aea9780ad217.jpg)

### Mockup input fields 
![profile-member_explained](https://user-images.githubusercontent.com/13672737/127755094-7b375e55-0f7c-491b-af93-a52dd2a9be56.jpg)

### Notes
1. All input fields are mandatory.
2. The description has a character limit of 100.

### Open Questions
1. Can we crop/compress profile images?
2. Can we integrate "map pins" from members later?
3. What happens with the existing data of members profiles ?

**Comment by chrismclarke** [comment]
We discussed this on the monthly call today and still need to get a few things sorted like how best to show the map pin, but for now still good if anyone wants to take on the frontend task of designing the card and profile pages based on existing data

**Comment by chrismclarke** [comment]
as for the open questions:

1a. Compress  yes (we already do that to resize all images to 1280px (I think) but might want to add an additional profile pic version (e.g. 360px or similar)
1b. Crop - no, but there's lots of good tools out there that could help us do that if it's something we want. Could create as a separate issue (would be a reasonable amount of work, but a nice feature to have for sure)

2. Mentioned on the call, yes we could just use the current country as the basis for some sort of pin, and then if we want user to be allowed to add a more specific location instead of default (middle of country) that can be in the settings. Will definitely need to think about how to display though as all pins for the same country would be default cluster in one space.

3. Probably just keep all legacy data in case we ever need to retrieve anything. If they have an existing cover image it will stay attached to their profile, but we just won't show it.

**Comment by tudi2d** [comment]
Happy to work on this in the next weeks 👍

**Comment by RaviAnand111** [comment]
Can I help ? 
Just tell me what I have to do ? @tudi2d  @chrismclarke

**Comment by tudi2d** [comment]
@RaviAnand111 Hey - thanks for the interest in contributing - feel free to give it a go! I will assign it to you - if you have questions feel free to reach out :)

**Comment by RaviAnand111** [comment]
guys I right now don't know reactjs, I just know javascript. Can I still contribute or should I learn reactjs in a week or so ?

**Comment by tudi2d** [comment]
Ok - maybe #1210 could be a good first issue for you then. You can get a feeling of the codebase & setup all the tooling. There are no specific React knowledge required for that issue & a first solution should be pretty straight forward. If you're interested comment in the mentioned issue that you will work on it :)

**Comment by chrismclarke** [comment]
Thanks for reaching out @RaviAnand111. In case you do find the platform a bit of a steep learning curve, I think there's a few suggested resources in the [Contributing](https://github.com/ONEARMY/community-platform/blob/master/CONTRIBUTING.md) notes. If any are outdated then you can also find loads of general react resources online. Or if you're the type who likes to learn whilst doing then the issue @tudi2d suggested sounds like a good one too.

**Comment by davehakkens** [comment]
Are you good with this @tudi2d? let me know if you need anything!

**Comment by tudi2d** [comment]
Thanks Dave - all good - just finished an exam & will work on this in the upcoming week 👍

**Comment by tudi2d** [comment]
<img width="849" alt="Screenshot 2021-11-14 at 21 51 21" src="https://user-images.githubusercontent.com/8904624/141749565-2dbdca0f-b036-4c37-881d-436439c48424.png">

Just a quick update: I started playing a bit around with this yesterday - if I find more time this week, I will create the PR. Does this look like you would expect? What should be the default image? (I just sketched smth. with Excalidraw here - just a placeholder)
