### ISSUE TITLE
[bug] - howto search persists after navigation

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#1238]
**Describe the bug**
When using the search box to find/filter howtos the sort order remains in the howto store regardless of any future navigation events. This is a bit confusing because the search param in the URL does disappear.

**To Reproduce**

1. Go to howto page
2. Enter text in search box
3. Follow howto link
4. Click howto in main menu bar to go to howto home page

**Expected behavior**
When the howto search param is cleared from the URL the howto page (e.g. following navigation), the howto list should also revert to default list. Similarly, if a user presses the back button on their browser to return to the search page both browser URL and search order should be preserved/displayed (currently correct)

**Screenshots**

**Additional context**

**Comment by MichalAndrejko** [comment]
This is something i'd like to work on, please assign me to this issue if available.

**Comment by chrismclarke** [comment]
Sounds great! Thanks @MichalAndrejko

**Comment by jparadasb** [comment]
Hey @chrismclarke and @thisislawatts, I was looking into this issue, and I found the following:

1. The search box is preserved in the "howtoStore" because when we navigate back to "howto" page, the SearchBox is fulfilled with the previous search text. This behavior is the same as the "selectedTags", the problem here is the component SearchInput is not triggering the onChange function when the "searchValue" is loaded.
![preciousplastic_1](https://user-images.githubusercontent.com/5114020/147450781-22f96ce5-77f2-427c-9ab7-248faa67ac1a.gif)


2. When I go history back after setting some filters, the "selectedTags" Component cannot catch the URL changes. I attached a GIF
![preciousplastic_2](https://user-images.githubusercontent.com/5114020/147450801-b2fedf4a-aa51-4eb6-857a-85e4dc204d9c.gif)

I made some fixes for those things, but I want to confirm if this is the expected behavior. I attached a GIF.
![preciousplastic_fixes](https://user-images.githubusercontent.com/5114020/147450966-729ac61b-5fea-48ae-9e59-b9c1be2376c8.gif)

* The search is kept in the URL while it is in the Store
* The filter box is sensitive to changes in the location, so it is possible go back or forward in the history

**Comment by thisislawatts** [comment]
Thanks @jparadasb for taking the time to look into this 🙏🏻 

I have pulled the branch down and built it locally.

> **Expected behavior**
> When the howto search param is cleared from the URL the howto page (e.g. following navigation), the howto list should also revert to default list. 

So if a user takes the following steps:

1. Loaded the howto listing page
2. 🔍 Search for _fish_
3. Clicked away to 'Events'
4. Navigated back to howto listing page
5. Expectation: Search field is empty

If I perform those steps on [your branch](https://github.com/jparadasb/community-platform/tree/fix_1238), I instead see the original search query _fish_ when we expect to see an empty search field. 

I am wondering if we should use the [`componentWillUnmount`](https://reactjs.org/docs/react-component.html#componentwillunmount) hook here to flush the store. What do you think?

Separately, the changes you have made to the TagsSelect look great :sparkles: It may be worth splitting those changes out to a standalone PR so we can iterate on them separately.

Have you had any success running the [e2e locally](https://onearmy.github.io/community-platform/Testing/end-to-end#getting-started)? I think it would be worth adding a new Cypress test suite to cover these flows. Let me know if you have any issues getting this up and running locally or would like to pair on them 😁

**Comment by jparadasb** [comment]
Great, I believe that `componentWillUnmount` should work. 

About the TagsSelect, could be a good idea to create an issue for it too, what do you think?

And regarding to running e2e locally, I'm getting this error 
```bash 
internal/modules/cjs/loader.js:613
    throw err;
    ^
```
when I run `yarn workspace oa-cypress start`, I'm using `node 12`.

**Comment by jparadasb** [comment]
I found to run the e2e locally using node 14. So I am going to take a look and let you know.

**Comment by thisislawatts** [comment]
> About the TagsSelect, could be a good idea to create an issue for it too, what do you think?
Sounds like a plan, please feel free to raise a separate issue to track that work.

**Comment by thisislawatts** [comment]
> I found to run the e2e locally using node 14. So I am going to take a look and let you know.

Thanks for flagging this issue with the e2e tests, that is unexpected behaviour. I would hope that we can keep the entire project tied to run with a single version of node. 

Out of curiousity, what tooling to do you use locally to manage multiple node versions?

**Comment by jparadasb** [comment]
I'm using nvm
