### ISSUE TITLE
[bug] Flags do not appear on `Where are you based?` input

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1351]
**Describe the bug**

![Screenshot showing alternative text fallback for flag image assets](https://user-images.githubusercontent.com/472589/147570960-2e0b613b-74e2-4945-af0a-9b7c4a32612a.jpg)

**To Reproduce**

1. Log into the platform site
2. Navigate to '[the user Settings page](https://community.preciousplastic.com/settings)', via Avatar > Settings
3. See error

**Expected behavior**

An image asset should be shown for each flag icon. 

Originally raised on Discord: https://discord.com/channels/586676777334865928/599284493525843984/925158014619635772

**Comment by thisislawatts** [comment]
Looks like it could be tied to this:
https://github.com/ekwonye-richard/react-flags-select/issues/65

**Comment by davehakkens** [comment]
Could see this being fixed as we find a  [solution for the map.](https://github.com/ONEARMY/community-platform/issues/1177)

Because up until it was always a bit vague since you had two ways to determine location.
1. Dropdown menu in profile for **members**
2. Add pin to map  in profile for **workspaces**.

I think having these 2 options caused some conflict before
Like here https://github.com/ONEARMY/community-platform/issues/1211

**Comment by thisislawatts** [comment]
@davehakkens I do not see this being tied directly to the map implementation.

At the moment there is a one to one relationship between a user and a map pin, but I think there is value in removing that constraint at a later date. I can think of a few scenarios where it is perfectly valid where a user may wish to be associated with a few geographic locations.

From what I understand #1211 is not caused by a conflict due to location being defined in multiple locations 🤔

**Comment by davehakkens** [comment]
I think before it had some conflicts that if users changed profile from member>workspace it could have different locations. (because the input fields used for members and workspaces are different for each profile)
https://github.com/ONEARMY/community-platform/pull/1153#issuecomment-844361997

That said, i don't really know what causes the problems or how to best go about it. 
It just always seems a bit unusual and perhaps more complex than it needs to be to have 2 different options to set your location. Could see this being made simpler with an update >one location setting.

But maybe i'm overthinking and this isn't an issue at all?

**Comment by thisislawatts** [comment]
Thanks for sharing the thread attached to #1153, from what I understand this is a conversation around a user country being stored on individual comments AND the original user. 

One design driven way to side step the comment flag issue completely would be to remove the country flag in favour of displaying a user avatar. Is there any reason we want to visually highlight the author's country more than the individual author's identity?

**Comment by davehakkens** [comment]
The main reason we use a flag is to make local collaboration easier and show the diversity of the global community. ( we use this more often on our platforms) +  we didn't have avatar upload integrated.

I've started this issue to visualize what a "want to get started pin" would look like.
Up for suggestions and feedback: https://github.com/ONEARMY/community-platform/issues/1362
