### ISSUE TITLE
Add useful button to Research module

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1405]
### Description

We have a useful button in our [how-to](https://community.preciousplastic.com/how-to) module. We need the same button in our research module ( will be used extensively in Project Kamp setup next season🔥)

### Page related

Will be used in :
- PR related to useful button https://github.com/ONEARMY/community-platform/pull/1097
- See the [research module](https://community.preciousplastic.com/research) 

### Mockup

![Add useful to research](https://user-images.githubusercontent.com/13672737/151038311-2a68f556-2d59-4730-a808-d9dae486a4a4.jpg)

**Comment by mmortar** [comment]
Hello, I am interested in adding this feature to the research module.  Could you please assign me to the issue?

**Comment by thisislawatts** [comment]
Hey @mmortar, thanks for picking up this issue it is really appreciated! 

Please let me know if you have questions or feedback on how you find working with the project. 

Speak soon! ✨

**Comment by mmortar** [comment]
Hey @thisislawatts,
So I've got the useful button created and doing everything it is meant to upon being clicked.  However, I'm struggling to get it to store the updated useful count.  I tried injecting as it was done for the HowTo module but this method doesn't work for the Research module because the button is not embedded in a class.  Please let me know if you have any ideas how to do this and I apologize if I'm missing a simple solution, I am new to typescript.  Thank you
<img width="525" alt="Screen Shot 2022-01-29 at 9 34 23 PM" src="https://user-images.githubusercontent.com/93676287/151684560-72251ce2-7a5c-4e1c-91ab-9140c77f9cd0.png">
<img width="659" alt="Screen Shot 2022-01-29 at 9 35 43 PM" src="https://user-images.githubusercontent.com/93676287/151684565-153c8b5f-e838-4e62-91c7-abb206d795a6.png">

**Comment by thisislawatts** [comment]
@mmortar could you push up the code you have got so far into a branch or draft PR?
