### ISSUE TITLE
@mention feature request

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1543]
Hey team,

Not sure how big a deal this is but as I was using the comments it came up the need of being able to mention users. 
Guess behaviour could be as follow:
User A @mention User B, User B gets a notification. 

Not urgent, but maybe nice to have in the future
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/17761877/158327349-bae411c9-b8a4-49dc-9c62-c76f829350dc.png">

**Comment by knoopx** [comment]
alright, taking this one. I suggest to start with a simple implementation and develop further as we go.

the bare minimum implementation is:

1) within the comment form submit handler, simply use a regex to match `@mentions` within the comment body
2) lookup the matched mentions to user ids and validate they actually exist
3) resolve the id of the page the user commented on and the id of the comment itself
4) create a notification for every matched mention id and the referring page/comment id. 

* notification text will be something like `User <username> mentioned you on <page title>`.
* whenever the user clicks over the notification, she will be redirected to the page the comment belongs to, and scroll height adjusted accordingly.
* mentions are highlighted and turned into links to corresponding user profiles
* no double notifications are triggered when the commenting user re-edits the comment?

for this to work we need:

* usernames to not contain spaces, otherwise will be very unreliable to parse mentions.
* comments to have unique html ids, so we can `scrollTo` corresponding html elements.
* commenting system to be somewhat properly abstracted, so that we don't need to re-implement mention handling all over the different sections/pages.
* be able to uncollapse comments if they are on request (when for example page#comment-n is given)

---

as a second stage, an auto-completion popup can be added:

1) the user types `@` and some characters and he gets a suggestion list of matching usernames above/below the cursor.
2) whenever he selects an username, we temporarily store the mentioning user ids alongside the comment body itself
3) when he submits the comment we already have all the necessary data to create the notification

---

I haven't checked (yet) how the data is modeled so this is pretty much a pseudo-implementation, please let me know if this makes any sense beforehand and if I should be aware of any other considerations.

**Comment by davehakkens** [comment]
hi @knoopx Sorry for the slow reply. Missed the notification on this one!
But sounds like a good plan forward. Exciting.
- Usernames are without spaces.
- Comments don't have unique html yet, we need to add that.

Let my double check with our maintainer to see if they have additional suggestions.

**Comment by thisislawatts** [comment]
Hey @knoopx, thanks for taking the time to write out your thoughts, really helpful. This sounds like a good implementation plan.

Following up on the requirements you've highlighted:

- ✅ usernames to not contain spaces, otherwise will be very unreliable to parse mentions.
  The usernames appear to be `A-z0-9\-`, although haven't seen the explicit requirement
- 🤔 comments to have unique html ids, so we can scrollTo corresponding html elements. – _This will need to be introduced, although the comments themselves have unique IDs so this will simple enough to expose_
- 😬 commenting system to be somewhat properly abstracted, so that we don't need to re-implement mention handling all over the different sections/pages. – _The UI components are reusable however there is some duplication in the controller layer, exploratory refactoring would likely be useful first step here!_
- 😬 be able to uncollapse comments if they are on request (when for example page#comment-n is given) – This behaviour doesn't exist at the moment and would need to be implemented. Some complexity here in managing the state, and we'd also want to spend some time considering the user experience. Scrollto behaviour, is useful but we may want to consider a background highlight similar to Stackoverflow. 

For example; the following link will take you to a specific comment on the page which is highlighted yellow for a second or two then fades to white. https://stackoverflow.com/questions/57118812/how-to-see-the-type-of-variable-within-android-studio-ide/59603462#59603462

**Comment by davehakkens** [comment]
hey @knoopx. Just checking in how this is going. Need help?

**Comment by davehakkens** [comment]
Let me know if you still manage to take this one @knoopx.
If not not worries but then we can free it up and assign to someone else!

**Comment by davehakkens** [comment]
Added for research and howto's
