### ISSUE TITLE
Useuful count -1

### ISSUE THREAD

**Issue by mattia-io** [ONEARMY/community-platform#1544]
I was browsing around on the how-tos and spotted this how-to with -1 count. Strange. 
When I click it goes to zero :) 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/17761877/158328874-ac71d49d-3540-4993-9d2f-1bb8b0810efd.png">

**Comment by chrismclarke** [comment]
I think this got fixed a little while back (we updated how the totals were calculated and recalculated all existing totals) so hopefully this shouldn't happen again - I just checked the db and everything is showing 0 or higher.

There might have still been a chance that locally could show the wrong number if the data not loaded in time for user to click, but that should be fixed with #1607 so I'll close when that is merged
