### ISSUE TITLE
[bug] Notification in research has how-to text

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#1676]
**Describe the bug**
We just added a notification when someone gives "useful" to a research topic.
However the text that is shown is "new comment on how-to"

I think this bug came after releasing this https://github.com/ONEARMY/community-platform/pull/1615

**Expected behaviour**
`How-to` should be replaced by `research`

**Screenshots**
<img width="273" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/168866023-a6f8944a-7b88-49c4-b360-aa14be681058.png">

**Comment by davehakkens** [comment]
'article title' is not shown at this point in notifications. (got to long)
Only general names `howto` or `research` are shown which link to the article

**Comment by Cabezaa** [comment]
Hi all, I have been trying to replicate this bug for doing my first contribution to this awesome project, but I haven't been able to replicate it. 

If I'm not mistaken, the bug should appear when someone touches the button "useful" from one of your research and you receive the notification right? If so, I'm seeing this correctly I think because it is tagged as Research:
![image](https://user-images.githubusercontent.com/13111453/169163887-32232665-f95f-4915-bffa-7e628869c156.png)

Also, if someone comments one of your research updates also is tagged as research (yes, here exists a little small error because have a capital letter and the other no):
![image](https://user-images.githubusercontent.com/13111453/169163793-4691a6c4-4145-418a-b464-f10629dca7ac.png)

Was someone able to replicate it? If so, could share the steps? 😃

**Comment by davehakkens** [comment]
thanks for looking into it @Cabezaa!
What you do is correct. But to be honest it doesnt seem to happen all the time, just occasionally.
Let me keep an eye on it and see if I find a pattern to replicate it
