### ISSUE TITLE
Help to migrate src/components/MoreContainer/MoreContainer.tsx

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1727]
We are looking to migrate `src/components/MoreContainer/MoreContainer.tsx` to `packages/components/src/MoreContainer/MoreContainer.tsx`

**Why?**

-   Improve structure of the components
-   Improve documentation for our existing components
-   Make it easier for our design team to review and refine the components
-   Decouple our components from application state
-   Convert our class based components to functional components
-   Allow reuse of our components outside of the primary single page application (SPA)#

**Definition of Migrated**

-   The component file exists in `packages/components/src`
-   There is a companion `*.stories.tsx` which includes an example for each use case of the component

**How?**

1.  [Create a new component](https://github.com/ONEARMY/community-platform/tree/master/packages/components#creating-a-new-component) in `./packages/components`
2.  Move existing component into new component
3.  Update all references to import the new component from `oa-components`
4.  Delete all files from `./src/components`

🐉 **Things to watch out for:**

-   If the original component file exported _multiple_ components these should be split into multiple separate files
-   If the component you're working on imports another component from `src/components` you will need to migrate that item first. Please make sure to claim ownership on the associated issue.
-   We want to use functional components, [read more around how to refactor a class component](https://nimblewebdeveloper.com/blog/convert-react-class-to-function-component)
-   You may spot an opportunity to create a new component to encapsulate some elements which are being used frequently across the UI. Yay, a new component is born 🐥
- The component may not need to exist.

**Comment by Xyli0** [comment]
Hi, I would like to work on this issue if you don't mind.

**Comment by thisislawatts** [comment]
Absolutely @Xyli0, I will assign this to you. Please let me know if you have any questions when working on this item.

**Comment by Xyli0** [comment]
I have looked into the problem and didn't find any difficulty, however while refactoring the component, I have a suggestion to make.

Currently, `MoreContainer` is not a flex container which forces us to include a flex element as it's first child to be able to center it's children.

I suggest to include this flex child element in the component since I guess children elements will always be stacked. 
I would use theme-ui `Flex` component and pass props from parent.

I would add as default `display: flex, alignItems: 'center', flexDirection: 'column'` and therefore clean the remaining Flex children elements in the codebase.

What are your thoughts about it?
