### ISSUE TITLE
[bug] Fixing fashion edit profile links incorrect

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#1730]
**Describe the bug**

Incorrect links in Fixing Fashion

**Expected behaviour**

#1 + #3 = https://community.fixing.fashion/academy/guides/profile
#2 + #4 = https://community.fixing.fashion/academy/guides/community-program

**Screenshots**

![FF urls](https://user-images.githubusercontent.com/472589/172067162-e5b96a8b-f827-4aa6-ad2c-117cfe7c262b.jpg)

**Comment by AlfonsoGhislieri** [comment]
Happy to pick this one while waiting for my other ticket to get reviewed

**Comment by davehakkens** [comment]
Great, go for it! These Fixing Fashion issues are a bit more challenging since it deals with our themes. (urls are different for each instance, Precious Plastic, Project Kamp, Fixing Fashion etc.) But you would be the first one ever to take an issue with theming! Good testing for us. Curiours if you would manage :)
If not let us know what is unclear!

**Comment by AlfonsoGhislieri** [comment]
So this should all be setup, only issue is that there seem to be some bugs when not on the precious plastic theme. To make sure everything worked I had to remove `.normal` from the theme badge inside of `Focus.section.tsx` (error message below). But the links are all good to go :)

<img width="867" alt="Screenshot 2022-06-10 at 11 52 18" src="https://user-images.githubusercontent.com/652368/173050086-9c51ac6c-30b8-4691-8321-b5de0211e162.png">

**Comment by davehakkens** [comment]
@AlfonsoGhislieri Project kamp doesnt use this yet (since they only have 1 profile type, members) 
That sidebar is still hidden...

<img width="1278" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/173913877-9e0593d8-f8ef-43f0-864d-c73567f77920.png">

Anyway seems to be merged so good to close, thankkkkss!
