### ISSUE TITLE
Release Categories Publicly 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#1969]
Time to release categories to the world 🎉
This feature been running in beta until now, we've now prepared how-tos + academy for its release. We're now ready to release categories publicly (out of beta-tester).

![categories](https://user-images.githubusercontent.com/17761877/193496924-b591ba01-bad7-44df-8d05-f6e5d0c401fb.jpg)

 This requires hiding tags dropdown from how-to overview page.

<img width="1370" alt="Screenshot_2022-10-03_at_05_33_59" src="https://user-images.githubusercontent.com/17761877/193497022-88396fa7-066d-419f-b33c-2689baf8836a.png">

**Comment by Sc4ramouche** [comment]
Hey there 👋 First-time contributor here 👀
I have a couple of questions:

1. Is this one is a "good first issue"? If so, I'd like to take a look and contribute (and let's add the label?)
2. Should we remove the `<AuthWrapper roleRequired="beta-tester">` in scope of this issue so that Category filter becomes available for everyone?

**Comment by Sc4ramouche** [comment]
Also, should tags still be displayed on the how-to cards?

**Comment by thisismattia** [comment]
Thanks @davehakkens 
@Sc4ramouche thanks for taking this on!
