### ISSUE TITLE
Hide events page 🥲

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2085]
Events page is struggling to be relevant and filled with content. Over 6mo with no new events. Which results in a poor UX for the Community Platform. 

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/17761877/216158738-8ee2f654-e87e-4d3b-81a1-5421d636985e.png">

Would be great to hide until we revisit it 🙏 I think this comes down to:
- Hide even page https://community.preciousplastic.com/events

I don't think users can access create event page https://community.preciousplastic.com/events/create except from events page (which would not be accessible), correct @davehakkens ? In which case no action needed.

I would also keep the little event badge for now (doesn't hurt)
<img width="197" alt="image" src="https://user-images.githubusercontent.com/17761877/216159395-e25f673c-445a-4bb4-b427-821133bc342a.png">

**Comment by asheerrizvi** [comment]
@thisismattia I can have a look at this. Also, where is this event badge visible?

**Comment by thisismattia** [comment]
Nice one @asheerrizvi thank you. The event badge is visible on profiles of users that previously made event. You can find an example here:
https://community.preciousplastic.com/u/plstico-precioso-uramba-

**Comment by thisislawatts** [comment]
@asheerrizvi the Platform consists of optional modules, which are [defined here](https://github.com/ONEARMY/community-platform/blob/master/src/modules/index.ts#L3-L12):

```ts
export enum MODULE {
  CORE = 'core', // This is enabled on all installations
  HOWTO = 'howto',
  MAP = 'map',
  EVENTS = 'events',
  RESEARCH = 'research',
  ACADEMY = 'academy',
  USER = 'user',
  ADMIN = 'admin_v2',
}
```

Note that neither https://community.fixing.fashion/ or https://community.projectkamp.com/ contain any mention of Events in their primary navigation. This is because the Event module is not enabled on that environment. 

The modules which are available within each deployment are managed using CircleCI environment variables as part of the build process. Specifically in this instance the CircleCI secret would be: `REACT_APP_SUPPORTED_MODULES`. To remove `Events` from Precious Plastic you will need edit access to CircleCI.

Relevant documentation: https://github.com/ONEARMY/community-platform/blob/chore/lint-cypress/packages/documentation/docs/Install.md#community-platform-maintainers

Let me know if there any further questions around this. Apologies that the documentation is hard to find. The absence of search in our documentation is a factor here 🔎

**Comment by asheerrizvi** [comment]
@thisislawatts thanks for this, I would've kept wondering lol. It seems like I cannot access the project on CircleCI

<img width="915" alt="image" src="https://user-images.githubusercontent.com/17976252/219354862-6d2d384f-7577-444c-8a70-8e647db6d6ee.png">

**Comment by davehakkens** [comment]
Do you happen to have access now you are a Github maintainer @asheerrizvi?

**Comment by asheerrizvi** [comment]
@davehakkens still seeing this 😞 

![image](https://user-images.githubusercontent.com/17976252/220330706-1d0f08f7-23fb-4288-86d4-5f2f3ea3bf6a.png)

**Comment by davehakkens** [comment]
I've been reading about it but can't seem to find a way to actually give access.
Found this button to "add team members" Gives this pop-up but doesnt copy any invite on my clipboard to paste..
<img width="1077" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/220736475-7e8adc5c-305d-4157-b57a-0282837d3a40.png">

So stuck there..
Maybe @chrismclarke knows?

**Comment by chrismclarke** [comment]
I think access is linked to github, so the main thing to make sure is that you log in using your github account (instead of username/password or gmail on the login screen)

Once logged in with github you will possibly need to configure circle-ci access to your personal github, done at
https://app.circleci.com/settings/user

![image](https://user-images.githubusercontent.com/10515065/224962297-ef5834d6-7eed-4662-8cad-7c9501e67e80.png)

If that still doesn't work then likely would require admin access to the organisation. There might be some workaround in https://circleci.com/docs/github-integration/#how-to-re-enable-circleci-for-a-github-organization but I haven't tried before myself

**Comment by thisismattia** [comment]
Top @thisislawatts you're the man!
