### ISSUE TITLE
[feature request] remove google analytics from platform in favour of privacy friendly alternative

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2188]
**Is your feature request related to a problem? Please describe.**
Google analytics has been deemed illegal under GDPR by multiple European regulators.  There are a number of open source privacy friendly alternatives, both paid and self hostable.

**Describe the solution you'd like**
Removal of google analytics in favour of a privacy friendly alternative.  I tend to use [plausible](https://plausible.io) but there are others that could also be reviewed for suitability.

**Describe alternatives you've considered**
Removal of analytics entirely - Assume a non starter as important to track usage of platform and features.

**Comment by thisislawatts** [comment]
There's a stale PR here, https://github.com/ONEARMY/community-platform/pull/2125, that looked into introducing Plausible, I had to pause my own Plausible subscription for the time being but feel free to take it over. I think the public dashboard is a compelling feature that should help demonstrate the value.

**Comment by davehakkens** [comment]
Got a two questions on this to understand better if the switch is worth it. 

1. Will a switch bring benifits for people reading the data (community managers) of introducing an alternative tool, like Plausible? For instance would it be better intergrated in the platform, deliver more specific statistics etc. If there are no benifits the switch is more of a downside since they need to learn a new tool.

2. Does a switch bring added benifits to our developers/codebase? For instance can it borrow certain stat/counting functionaility or give better insights for testing etc. (Can't tell if it just replaces Google AN or can do more, since it seems to have more [dev docs](https://plausible.io/docs/) and stuff.

**Comment by iSCJT** [comment]
@davehakkens

1. Do you have an overview of what data the community managers want to see, and why?  One thing Plausible can do is have a public stats page which you could embed into an admin view or have more widely available, example: https://plausible.io/plausible.io

2. I think it's a neutral change from a developers perspective, apart from initial setup it's not something you really need to ever touch in my experience.

The majority of the benefits as I see it are for the end user and privacy.  You can get all the stats you'd legitimately want organisationally without tracking individual users and giving google a load of data to sell them stuff.

**Comment by davehakkens** [comment]
No specific data in mind. We did add a few event trackers like comments or useful to keep track of the amount of times those buttons are used. That was quite useful, but actually more for dev then community manager.Anyway that [dashboard](https://plausible.io/plausible.io) should provide enough for now, would this be possible to intergrate in the admin panel we use? That would be a great addition for community managers to have the stats more close by.

Overal the platform still has many features, optimizations and bugs to work on. Privacy is very low on the priority list since both the projects that use the software, users and community managers are not bringing this up. The other areas are simply more painful for them atm.

That said if it's easy to intergrate we could just give it a try! Perhaps keep both running for a few months to test out and see if we like it?
