### ISSUE TITLE
[bug] previously used how to & research slugs not prevented from being used

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2315]
**Describe the bug**
If the title of a how to or research item is updated then the slug is also updated, previously used slugs are saved for that item so that old links can be maintained however nothing prevents a new item from being created with a previously used slug.

**To Reproduce**
Steps to reproduce the behaviour:

1. Edit how-to / research item and change title
2. Open item using original and new slugs to confirm that accessible using both
3. Create how-to / research item and use the old title of the previous item
4. Complete details of item and submit
5. Observe that new item uses original slug and loads correctly but that it is not possible to access the edited item using the original slug.

**Expected behaviour**
That current and previous slugs are globally unique across item type.

**Screenshots**

**Additional context**
My suggestion is a global lookup table of slugs and corresponding document id's which is checked before assigning a slug.  If a slug is in use then either return the existing error about the title not being unique or auto append an incrementing number.

**Comment by benfurber** [comment]
✋ Happy to pick this up. 

Any thoughts on the best way to test this? I don't think(?) how the store mocks are currently setup will suit this and I don't think extensive e2e should be needed for what will end up being a little util.

**Comment by benfurber** [comment]
Actually, maybe not me(!) I think I'll need a little more handholding on where to start with creating new collections through firebase.

**Comment by benkelaar** [comment]
I wouldn't mind picking this one up.

@iSCJT Why add a new lookup table?  I think we can query the documents based on the previousSlugs [here](https://github.com/ONEARMY/community-platform/blob/master/src/stores/common/module.store.ts#L40) and then check those against the current identifier as well.  I'm totally new to this codebase, so I might be missing something though.

**Comment by benkelaar** [comment]
I think what I've done now should fix the issue.  However leaving it in Draft for now since I need to look into unit tests and testing it manually.  Feel free to review current status.

**Comment by benkelaar** [comment]
While investigating the tests I found the fix is even easier.  Since all current slugs that are in use are actually also pushed to the previousSlugs array, it's just a matter of changing the query condition from `slug == slug` to `previousSlugs array-contains slug`.

I also did a small refactoring so the code made a little more sense to me (Basically moved validation logic up to the validators file to keep the store logic database-related.  Let me know if that's undesired.

**Comment by benkelaar** [comment]
So I do have a concern, coming out of the tests as well.  The test data for the research items did not contain previousSlugs arrays at all, does this mean that there might be how tos or research items in production databases that don't have this property either?

Do you guys do database migrations?   Because I couldn't find any so far, but that might be a good mechanism to fix this.

Otherwise I'll have to go back to the earlier case of querying both on slug and on previousSlugs.  Please let me know what you prefer.
