### ISSUE TITLE
[bug] window modal appears about unsaved changes after publishing Howto

### ISSUE THREAD

**Issue by AlfonsoGhislieri** [ONEARMY/community-platform#2317]
**Describe the bug**

A window modal appears prompting the user to confirm if they want to leave the page because there are unsaved changes. This should not be happening as the Howto is already uploaded and there should be no more unsaved changes on the page.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'howto' 
2. Click on 'edit'
3. Make changes to any section (eg: description)
4. Click on publish
5. Try and leave page by clicking 'view Howto' or another way
6. See error

**Expected behaviour**
There should be no window modal appearing once the HowTo has been uploaded.

**Screenshots**

![image](https://user-images.githubusercontent.com/652368/236061356-809c6989-d9cb-48bb-bca5-02e9d60f903a.png)

**Additional context**

**Comment by kyle-skaxx** [comment]
Is this bug still active? I'd love to have a crack at it

**Comment by iSCJT** [comment]
Yes it's still there @kyle-skaxx, thanks for taking a look.  I'll assign the issue to you.

**Comment by iSCJT** [comment]
@kyle-skaxx did you get to take a look at this one?

**Comment by kyle-skaxx** [comment]
@iSCJT Hey, yes I've taken a look at it and sorry for the inactivity life has been hectic as of late(nevertheless i am more than willing and able to contribute).

I noticed that the "Publish" and "Save to Draft" buttons in the Howto.form.tsx file appear to have the same `onClick` function assigned to them. As a result, when either button is clicked, it seems to trigger the same action.

![image](https://github.com/ONEARMY/community-platform/assets/112350799/92370011-8b0a-416a-ae56-bec91eeaf7f0)

Taking closer look at the `trySubmitForm` being passed, the form submission is triggered by dispatching a custom submit event on the `formContainerRef` element. This can lead to a scenario where the browser detects unsaved changes because the form state may not have been properly updated or cleared after the submission.

![image](https://github.com/ONEARMY/community-platform/assets/112350799/23e876e3-7c3d-4261-9328-f1ad525896af)

I am currently in the process of reading the final-form docs to come up with a proper solution.

**Comment by benfurber** [comment]
✋
