### ISSUE TITLE
[bug] Admin – Rendering for multiple notifications per user

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2326]
**Describe the bug**

With many notifications the design of the page gets weird

**Screenshots**
<img width="1443" alt="AdminNotifications" src="https://user-images.githubusercontent.com/472589/236497572-7f8cb9ac-274f-4f24-a88e-3330e78ef40d.png">

**TODO**

- [ ] Remove padding from notifications container

**Comment by asheerrizvi** [comment]
@thisislawatts I can try this one as well. How should we address this? Make the row grow in height?

**Comment by davehakkens** [comment]
Seems to be sort of fixed? 

https://github.com/ONEARMY/community-platform/assets/13672737/d226bd1d-f7d4-4034-a631-5dd53bbac871

**Comment by asheerrizvi** [comment]
@thisislawatts @davehakkens  I think we should allow the row to grow in height. If that is not a viable option then a scrollbar is fine. What do you guys think?

**Comment by davehakkens** [comment]
At this point its hard to estimate how many rows will be shown there (still testing notifications)
So displaying all might results into a very long/weird page.

Might be better to leave scrollbar behaviour for now. But could be improved by removing the top and bottom padding. so it can show more rows instead of white space
