### ISSUE TITLE
[feature request] send email notifications when how-to/research/map pin approved or 'rejected'

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2379]
**Is your feature request related to a problem? Please describe.**
Users do not currently know if their post has been approved or needs amendments before being approved.

**Describe the solution you'd like**
Email notification to be sent when how to or research article is approved or rejected.  Email should include link to post and if 'rejected' include [comments left by admins](https://github.com/ONEARMY/community-platform/issues/2377)

Need to include new map pin status needs improvement as well (clarify exact naming).

**Describe alternatives you've considered**
User continues to log in to check if post approved.

**Additional context**

**Comment by thisislawatts** [comment]
@iSCJT is this useful without the _comments left by admins_ work or should we consider this blocked by #2377?

**Comment by iSCJT** [comment]
@thisislawatts I think it would still be useful as a standalone but agree nicer to implement following 2377.

**Comment by thisislawatts** [comment]
@iSCJT given the dependency on #2377, should we remove it from the June sprint?

**Comment by iSCJT** [comment]
@evakill I've added a pr for displaying the comments now, do you want me to look at this or do you think you'll still have time to?

**Comment by evakill** [comment]
@iSCJT if you have time to pick it up, go for it! and if you want we can pair sometime this week

**Comment by iSCJT** [comment]
@sigolenej if you could add required wording one this ticket that would be appreciated.

**Comment by sigolenej** [comment]
Thanks @iSCJT ! 

Can you confirm these will be sent by the community@preciousplastic.com email? 

In regards to the design, if it will look like a normal email for the user (which is fine), can we include our automatic signature?
![Screenshot 2023-07-27 at 16 21 51](https://github.com/ONEARMY/community-platform/assets/138245356/15e24614-a029-47b6-8985-dd0ba17a92be)


Here are the emails we currently send to humans related to their HT. 

We have been using dynamic content, that will be shown between " {} ".

                1. How-To submission confirmation
**_---- Title ---_**
Your How-to -{HT title}- has been submitted

**_---- Content ---_**
Hey {username},

Your How-To -{HT title}- has been received! 

Our team is currently reviewing it and will get back to you within a few business days. 

Thank you for taking the time, the community will benefit from this knowledge and more plastic will be recycled thanks to YOU. 

Cheers,
Charlie your Precious Plastic Community Manager

                2. How-To approval
**_---- Title ---_**
Your How-to -{HT title}- has been published!

**_---- Content ---_**
Hey {username},

Huzzah! Your How-To -{HT title}- has been approved.

It is now visible on the community platform: {HT url}.
Users will now be able to comment and mark it as useful.

Thanks for sharing your knowledge!
Charlie your Precious Plastic Community Manager

cc @thisismattia

**Comment by sigolenej** [comment]
Thanks ! 

Adding the map pin emails :) 

                1. Map pin submission confirmation
**_---- Title ---_**
{username}- Your map pin has been submitted

**_---- Content ---_**
Hey {username},

Your map pin has been submitted.

Our team is currently reviewing it and will get back to you within a few business days.

Cheers,
Charlie your Precious Plastic Community Manager

                2. Map pin submission confirmation
**_---- Title ---_**
{username}- Your map pin has been approved

**_---- Content ---_**
Hey {username},

Huzzah! We are happy to inform you that your map pin has been approved and it is now visible!  👐
You can check it out here: {profile url}.

Don't forget to check out the other Precious Plastic platforms: 
----> How-To's: where you find or share interesting ways to make new things. https://community.preciousplastic.com/how-to

----> The Bazar: a marketplace dedicated to plastic recycling. Make sure to sign up as a seller to increase your reach and sales. https://bazar.preciousplastic.com/apply/

Thanks, 
 Charlie your Precious Plastic Community Manager

**Comment by sigolenej** [comment]
Hey hey ! where do we stand on this? :)

**Comment by evakill** [comment]
hi @sigolenej, thanks for posting the templates here. sean has been out working on another project this month, so progress on this one is on pause right now. understand that this is high priority for PP, so if i have extra time this week i will try to pick it up or open it up to community development.

**Comment by sigolenej** [comment]
Hey @evakill thanks for this, would be great, at least for the approved & rejected ones 🙏

**Comment by thisismattia** [comment]
@evakill just double checking we're on the same page, this item is PP priority for september :)

**Comment by evakill** [comment]
you got it @thisismattia @sigolenej! i'll be taking over work for this one

**Comment by evakill** [comment]
@sigolenej the how to approval email is under review! i included a screenshot - you can check out the design at https://github.com/ONEARMY/community-platform/pull/2792. i used the same template as we do in the notification emails so that we could reuse code and have a consistent design! let me know what you think. 

next up i will do the same for the map pin approvals. do you have the message and subject line for the rejected emails? my understanding was that those were more important than the submission emails, so wanted to do those next. 

but now that the system is set up, should be much quicker and easier to add or edit email content :)

**Comment by sigolenej** [comment]
Hey @evakill thanks !! 
Great news. To make if a bit fun, could we add a fun GIF to the email? 

In regards to the content of the map pin approval and rejection email, you can see them in the above comments :) Let me know if i should send them again. 

Yep in prio order: approval/rejection emails for HT & map pin, needs improvement email, badge given 

Thanks

**Comment by evakill** [comment]
> In regards to the content of the map pin approval and rejection email, you can see them in the above comments :) Let me know if i should send them again.

ah sorry @sigolenej i feel like i'm missing something! i see _submission_ and _approval_, but not rejection? if it's not too much trouble, could you please repost that one?

thanks for listing the priority! got it 👍

as for the GIF, let me make sure i get all the base templates done first and then we can spice them up!

**Comment by evakill** [comment]
edit: i found the comments in [this issue!](https://github.com/ONEARMY/community-platform/issues/2668#issuecomment-1653827277) want to confirm these are the rejection templates that you would like? @sigolenej

**Comment by sigolenej** [comment]
Ok for the GIF :) 
This issue is the content for "needs improvements". 

Can we change the signature of all emails to "The Precious Plastic Team"?

Below the content for rejection of map pin & HT:

Thanks @evakill , let me know when i can test it!

**MAP PIN**
Subject: 
 {username} - Your map pin has been rejected 

Content: 
Hey {username},

Thank you for applying to be on the Precious Plastic Map. 

Based on the content provided in your profile, we were not able to see that :
(1) your work is related to recycling plastic,
and/or 
(2) you work on small-scale recycling. 

If we have misunderstood, complete your profile and re-submit your request :)

Check the profile guidelines*, and make sure the 2 points above are clear.
    * (URL to be embedded in the text "guidelines" https://drive.google.com/file/d/1fXTtBbzgCO0EL6G9__aixwqc-Euqgqnd/view

We hope to see your edits soon,
Thank you,
The Precious Plastic Team

**HOW-TO**
Subject:
 {username} - Your How-To has been rejected 
Content:
Hey {username},

Thank you for submitting your How-To. We appreciate your contribution and the time and effort you put into creating it.

However, after reviewing your submission, we feel that it does not contribute to small-scale plastic recycling.

Feel free to edit and re-submit it :)

Thanks, 
The Precious Plastic Team

**Comment by evakill** [comment]
approval, submission, and rejection emails are now in prod under beta testing!

the needs improvement emails are covered in this issue: https://github.com/ONEARMY/community-platform/issues/2668
and we will address beta feedback as it is raised.
