### ISSUE TITLE
[test] to cover display of how-to and research on member profile

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2443]
Add tests to cover functionality introduced in https://github.com/ONEARMY/community-platform/pull/2428

Test cases:

- Moderation statuses are filtered correctly (only accepted shown)
- Section only displayed to beta testers
- Behaviour when how-to's or research fetch from database fails
- That links work successfully

**Comment by benfurber** [comment]
I'm happy to start looking into this now.

**Comment by iSCJT** [comment]
Thanks @benfurber, I'll assign you.

**Comment by benfurber** [comment]
I've covered off "section only displayed to beta testers" and "that links work successfully" so far in #2505.

One request. I've had a little look at trying to understand how the moderate flow works but I haven't gotten my head around it yet. Could a quick comment be added here to explain it please or maybe @thisislawatts can show me when we pair next week?

One challenge. This again might be due to my limited understanding of the system currently, is it realistic that the site could be up generally but that the how-to's or research DB calls would fail? Thus does this scenario really need to be covered.

Thanks!
