### ISSUE TITLE
[feature request] display all images uploaded by a member or space on their profile

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2490]
**Is your feature request related to a problem? Please describe.**
Users can upload multiple images to their profile in the settings section but only the first image is displayed when viewing their profile.

**Describe the solution you'd like**
Display all uploaded images either with thumbnails to click through or a carousel.

**Describe alternatives you've considered**
Keep current behaviour.

**Additional context**

**Comment by davehakkens** [comment]
If I get it correct this is new feature? Adding an image gallery for users to upload images besides their profile picture

I don't think this is needed for member profiles since we like to keep those simple for now.
Could be useful for space profiles since they have a lot more images to show. But think it would need some design work first to intergrate properly.  That said also up for building the function, release for beta-testers and iterate along the way.

Might be good to clear up what we want before merging https://github.com/ONEARMY/community-platform/pull/2491

**Comment by alessandro-massarenti** [comment]
The way I envisioned it (if I got it correctly) is that in the settings you can already add up to 4/5 pictures of yourself or your space.

I so used those pictures in the card showing your profile.

Like in this image:
![Schermata del 2023-06-27 22-27-48](https://github.com/ONEARMY/community-platform/assets/48263116/3a449af3-93f5-46d5-8cd8-29d9df6ee030)

Moreover, in the PR they said an already implemented carousel should be used. That in my opinion is of course a great idea.

**Comment by thisislawatts** [comment]
@ONEARMY/design is this something we want to do or shall we close it out for the time being?

**Comment by davehakkens** [comment]
Can be removed. 
the original issue was a bug, that got fixed. 
@alessandro-massarenti made a nice new feature but needs a bit more design to intergrate with profiles
