### ISSUE TITLE
[feature request] integrate patreon login and add supporter badge

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2537]
**Is your feature request related to a problem? Please describe.**
We would like to link the supporter badge on the community platform to whether a user is supporting the project on patreon.

**Describe the solution you'd like**
- Link to your patreon account button in member settings.
- Save patreon account email to user record
- Save date they began supporting the project to user record
- Web hooks for changes in supporter status on patreon to call google cloud function and update details accordingly.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by AlfonsoGhislieri** [comment]
I'll have a crack at implementing this, I'll add it to the September milestone

**Comment by davehakkens** [comment]
how is this cracking @AlfonsoGhislieri?

**Comment by AlfonsoGhislieri** [comment]
I started on it this week, was busy with work and some other issues so going to try and get this done in the next week!

**Comment by davehakkens** [comment]
done sounds ambitious! Very curious how/if this would work out

**Comment by pizzaisdavid** [comment]
I looked into this a little bit, here are some technical notes of what I found.

But first a very short demo:

![Screencast from 11 10 2023 18 28 43](https://github.com/ONEARMY/community-platform/assets/4391884/e8451703-4cde-44c9-87a4-299610d957f3)

You can see the code as it is currently on this branch: https://github.com/ONEARMY/community-platform/compare/master...pizzaisdavid:community-platform:oauth?expand=1

As Alfonso pointed out, Patreon doesn't have a test environment. So one way to do some testing is for people to create their own Patreon Creator account. You can see mine here: https://www.patreon.com/TestTestTestTestTest649

I think to be able to publish the page, I needed to have either least one product or a membership. I made a simple product:

![Screenshot from 2023-10-11 18-46-12](https://github.com/ONEARMY/community-platform/assets/4391884/4825870f-d67c-403d-add6-691ac4b5e812)

I avoided setup up a membership because I wanted to be able to test that without paying. I don't know so much about Patreon, so I can't say clicking the "Join for Free" on my page will be the same as a paying member. But with this method we can at least develop and test the login button.

In order to setup the login button, some configuration would eventually need to be done on the actual production account.

Here is what mine looked like for the demo:
![Screenshot from 2023-10-11 18-54-39](https://github.com/ONEARMY/community-platform/assets/4391884/c99b989b-86f9-4cd7-910d-f52d131ac2bd)

Thinking about how this ticket is described, if I understand correctly, it is somewhat two independent systems:
1. Setting up the login and storing some initial data.
2. Constantly listening for updates.

For the first point, the next step would be to create a backend endpoint. (In the [docs, either step 3 or 4, I'm not sure which, sorry.](https://docs.patreon.com/#step-3-handling-oauth-redirect).)

About point number two:
As I understood it, in the initial ticket description, it mentions that we want to save the user email to be able to compare for updates. People may want to check if there is a user id or something else, as it is possible for users to change their email address on the Patreon platform -- which I imagine could cause problems. But maybe there is an event to listen for email changes, to be honest -- I didn't check.

Also, I would if there isn't already data coming via other webhooks (I see there are discord and slack in the codebase, but those seem to be sending data.) Anyways - so if there isn't already webhooks listening for data in the backend, I would consider a different approach, instead making regular requests to the Patreon API and caching them instead. Why? Because if you have downtime on production or a bug in the code listening for events, you might miss some events. Which could cause problems, like people remaining being marked as supporters even though their subscription was cancelled. But maybe that was already spoken about and it may come with its own set of problems.

**Comment by AlfonsoGhislieri** [comment]
Thanks for taking the time to write this all up @pizzaisdavid and implement it using a frontend redirect approach, we definitely need to handle this process server side though for obvious security reasons. I'm currently fighting with the emulators to be able to test the creation of a cloud function to handle the authentication process following the redirect from patreon....

I wouldn't worry right now about the webhooks and listening for updates. Definitely best to break this issue down and first focus should definitely be to setup the authentication process and make sure it is tested thoroughly and that the information is saved in the User document. Since there's still quite some work to be done here!

**Comment by evakill** [comment]
see #3068 for badge
