### ISSUE TITLE
[change] wording of how-to 'embed a youtube video' description

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2557]
Wording of how-to embed a youtube video field is confusing and implies the field is mandatory.  

Change the two labels to one label, "Upload image(s) or a video" 

See here: 
![image](https://github.com/ONEARMY/community-platform/assets/37253846/dd99ffb2-01de-4abc-b2c3-a9ab06ebefae)

**Comment by evakill** [comment]
@sigolenej Have you gotten a chance to think about this one?

**Comment by sigolenej** [comment]
The issue here is that even if we change the wording of the sentence, the layout doesn't make it clear that it is one or the other...

-> could we create a drop-down option with IMAGE // VIDEO and then have the respective upload option (images or URL) ?

If not, we can propose a short term re-phrasing solution 

cc @thisismattia

**Comment by thisismattia** [comment]
Hey @evakill thanks for following up on this. 

The issue seems to be hierarchy where we have 3 equal blocks (title, description, media/content) with the media block consisting of 2 subitems (images + video). Now either you have additional smaller headings to convey that further hierarchical breakdown or leave the subitems without a heading. Not sure if this is clear. 

Here is an attempt to sketch
![Group 1](https://github.com/ONEARMY/community-platform/assets/17761877/d5258bc1-d221-405d-bbc5-8bdc1f387062)

Not ideal as the video block is quite confusing imo

**Comment by iSCJT** [comment]
@thisismattia @sigolenej does it definitely have to be one or the other?  Couldn't we let people add both?

**Comment by sigolenej** [comment]
In the scenario were an author would add both, how would this be shown? 
The same layout as when an author adds multiple images but one would be a video? Would the video be automatically first?

**Comment by sigolenej** [comment]
@thisismattia should we include this in the other issue where we are discussing the layout of the HT?

**Comment by thisismattia** [comment]
Ye we could also add both. That might actually make everyone's life easier.
@davehakkens any thoughts?

**Comment by davehakkens** [comment]
I would say both is prefered but not done because it was hard to implement.
But up for taking that as the preferred solution foward.

Due note this makes the issue much bigger, needs design work and will take much longer to implement.
I dont know how urgent the issue is but changing words like the original issue can be a simple fix in the meantime.

**Comment by AlfonsoGhislieri** [comment]
Just coming to check back on this, do we want to temporarily still change the text while re-thinking the design?

**Comment by evakill** [comment]
@AlfonsoGhislieri yes! this was discussed at the meeting - i updated the description to reflect the scope of work that we decided to move forward with at this time.

**Comment by ericblois** [comment]
@sigolenej @thisismattia hello, am new to contributing and figured this little temporary fix is a good way to introduce myself :)
