### ISSUE TITLE
HT typo bug

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2664]
Issue 
In the how-to the search text placeholder says "Search for a How,to". 

Solution 
Change to "Search for a How to"

<img width="274" alt="Screenshot 2023-07-14 at 12 02 50" src="https://github.com/ONEARMY/community-platform/assets/17761877/73931be5-2eb2-43ac-a225-79df45a48496">

**Comment by asdFletcher** [comment]
Good find, I'm happy to fix this one!

I was thinking about making a variable to use across the different places we display the wording "how-to" to the user. I noticed that it is not displayed the same in all cases, does this matter?


![image](https://github.com/ONEARMY/community-platform/assets/42685363/6e3ceb15-1b75-400b-b49e-83aee86d0e4b)

What do you think about changing it to `Search for a How-to` instead of `Search for a How to`?

**Comment by asdFletcher** [comment]
I will be out for the next 4-5 days, so if someone else wants to take this feel free. Otherwise I'm happy to work on it when I get back
