### ISSUE TITLE
[feature request] add thumbnail images to the research listing page

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2682]
To include picture and better indication of what the 3 icons / numbers mean for each research item.

**Comment by davehakkens** [comment]
### **1. Include thumbnail images** 

We want to add thumbnail images to the [research overview ](https://community.projectkamp.com/research)
<img width="913" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/9e2af69f-4942-48a4-9d07-99366dd00cb6">

We have two options.
1. User uploads a custom thumbnail when starting a research
2. It always shows the latest uploaded image in a research. (same as when you share a research url in Slack or Discord, it generates a preview of the latest image posted)

Option two would be prefered since it makes the page more dynamic, you can have a glimpse of the update and when starting a research you dont often have a good image. This comes along the way as you start.
But also aware option two is a bit more unusual, so happy to get some dev input

**Comment by evakill** [comment]
thanks @davehakkens - marking this issue as ready for dev, implementing the thumbnail images with option 2 as you described. going to move the tooltips into a separate issue

**Comment by earlbalai** [comment]
> ### **1. Include thumbnail images**
> We want to add thumbnail images to the [research overview ](https://community.projectkamp.com/research) <img alt="afbeelding" width="913" src="https://user-images.githubusercontent.com/13672737/256573167-9e2af69f-4942-48a4-9d07-99366dd00cb6.png">
> 
> We have two options.
> 
> 1. User uploads a custom thumbnail when starting a research
> 2. It always shows the latest uploaded image in a research. (same as when you share a research url in Slack or Discord, it generates a preview of the latest image posted)
> 
> Option two would be prefered since it makes the page more dynamic, you can have a glimpse of the update and when starting a research you dont often have a good image. This comes along the way as you start. But also aware option two is a bit more unusual, so happy to get some dev input

I did something similar when I built the news cards for a client project, I basically just pulled the latest image attached to the post since all images in a post either uploaded as a custom or uploaded as data within the post itself. If also ran a conditional to see if the post is using a custom, if not then pull the most recent image from the post data. This kept it super dynamic.

**Comment by goratt12** [comment]
Me and Jakke are working on it, Commit coming soon...
