### ISSUE TITLE
[design needed] add username / map pin title search to map

### ISSUE THREAD

**Issue by iSCJT** [ONEARMY/community-platform#2685]
Design needed for adding search by username and map pin title to map page.

**Comment by sigolenej** [comment]
@evakill can we do as suggested in the meeting to go for the simple option of just adding a search via map pin name box for this?

**Comment by davehakkens** [comment]
@sigolenej Is this an urgent missing feature?

Discussing this it would make more sense to intergrate this search in a member table-view directory. 
This contains more text based data and would allow to include other filters like finding verified or supporters.
How do you feel about closing this in favour of focussing on building a member directory?

**Comment by sigolenej** [comment]
I think it would be nice to have to be able to search via the map pin name. 
Today I find the address search to not have the best UX & I really don't find it easy to find a WS (other than knowing where they are & zooming in). 
What do you mean when you refer to a member directory?

**Comment by thisislawatts** [comment]
@davehakkens, @sigolenej sketched something out with search by username functionality.

![Screenshot 2023-09-05 at 21 19 58](https://github.com/ONEARMY/community-platform/assets/472589/8f6cbd42-a808-43b9-92a4-ef3cbe626266)

Available to play with at: https://onearmy-next--pr2748-spike-directory-list-aatgm7p7.web.app/directory.

Note. We will need to join the Map Pin data with the full User record to get all of the information. The code at the bottom of each card prints out all of the information available within the Map Pin object.

**Comment by thisismattia** [comment]
This is very cool ♥️ thank you @thisislawatts 
Indeed a member directory as previously talked @davehakkens makes a lot of sense but needs quite a bit of thinking/design upfront. Nevertheless this is exciting and working towards the idea of making profiles stronger

**Comment by davehakkens** [comment]
Thanks @thisislawatts 

I roughly see two options forward here and made a layout for each.
Don't get distracted by the design, the main reason is to try and figure out what approuch fits our needs better:
For the projects @thisismattia and @sigolenej and dev @thisislawatts 

## Option 1.
![member directory _map-pins](https://github.com/ONEARMY/community-platform/assets/13672737/06fa9e77-24ca-4616-9b4c-b2df16b37d4b)


Based on what Luke made above. We use this data to display all the map pins in a list view. Based on this we can add the option to search, filter supporters and verified.
- It only shows account with an approved map pin (So not all workspaces)
- Only members with a "want to get started pin" can be found.
- Won't be able to show all supporters (since not all have a map pin)
- All accounts you click have good accounts since they are moderated
- Faster to develop
- Faster to load since its less data
- Total members amount is low



## Option 2.

![member directory _all members](https://github.com/ONEARMY/community-platform/assets/13672737/3360c33a-b419-4092-a11b-60cb5aaabd70)

We make a directory to browse all members and use the data from their profiles.
- It will load all users (including those with poor, or none information)
- We can add more filter metrics (most useful, member since, has map-pin etc)
- Every user and supporter can find their account
- Takes longer to develop
- Large dataset to load fast and optimize
- Total members is high.


My personal conclusion: I think only showing map-pins (option 1.) might be to limited since it will leave out users that don't "want to get started" or workspaces without approved pins. But including all users might be not worth it since it needs to load a large datatset and +/-85% of users has incompleted profiles since they only made an account to download/test or useful things. Perhaps the way in the middle is > Display users like option 2 but only show user that completed their profile?  (so [users in column 3 here](https://ibb.co/X4MZfGr))

Any thoughts or preferences?

**Comment by thisismattia** [comment]
Hey @davehakkens looking good. And more importantly useful. 

I personally  prefer option #2 as it seems more valuable to the user. 
Regarding the loading, maybe adding pagination so it only shows 25-50 items could help?

Potentially Option #1 is v1 of the member feature only showing people on the map (even though not sure it is the point of this feature) and option #2 is v2 developed at later stage. Assuming the code can build on each other.

**Comment by sigolenej** [comment]
Hey @davehakkens what is the status on this? Would like to understand what would be the next steps here and in whos ball is it to follow up on this :)

**Comment by davehakkens** [comment]
Low priority atm.
Its on our to do list for winter-design
