### ISSUE TITLE
[bug] Saving an item as draft with a slug that is in use causes URL collision

### ISSUE THREAD

**Issue by evakill** [ONEARMY/community-platform#2744]
**Describe the bug**
When you save a draft howto, you are allowed to use a slug that is currently used in another howto. This causes an issue when you navigate to your draft howto, as it shares the same URL as an existing howto.

**To Reproduce**
Steps to reproduce the behaviour:

1. Find an existing how to slug
2. Create a new howto with the same slug
3. Save as draft
4. Click on your draft how to
5. You will be navigated to the existing how to, not your own

**Expected behaviour**
Should not be able to save a draft howto with the same slug as an existing howto. 

**Additional context**
Use the same validation requirements for drafts and publishing for the title field

**Comment by goratt12** [comment]
Because we are using the slug as the howto ID (a user can fetch/edit a howto by it), 
shouldn't the expected behavior be that you cannot create a new howto with the same slug (ID)?

I noticed that the howto document has _id field, we can change the URLs for viewing/editing a howto to be
`/how-to/:slug/:id`
`/how-to/:slug/:id/edit`
and prevent the behavior

**Comment by evakill** [comment]
>shouldn't the expected behavior be that you cannot create a new howto with the same slug (ID)?

yes - sorry if the description wasn't clear but the expected behavior is that you cannot create a how to OR how to draft with the same slug. 

> I noticed that the howto document has _id field, we can change the URLs for viewing/editing a howto to be

this would indeed solve our uniqueness problem, but i think it's desirable that the URLs are human-readable instead of containing a random UID string like `038gjWgLjiyYknbEjDeI`.

**Comment by goratt12** [comment]
Sounds good! 
I can develop the fix

**Comment by goratt12** [comment]
@evakill 
The PR I created fixed the issue, by the Cypress test are failing because the test try to create a draft with a short title: 'qwer'.
Because I changed the code so the title have to be validated even if its draft (to check for duplicate), the test fail.

Do you think I should change test so it will check if a draft can be created with a valid title, or change to code to disable all validation for title in draft mode except duplicate validation?

**Comment by thisislawatts** [comment]
This is a really useful bug to fix, thanks for taking a look @goratt12. I really appreciate the time and energy you've already spent on it. 
Thanks for addressing this bug, @goratt12. Your efforts thus far are truly appreciated.

Our current software design uses the Title field to generate a URL friendly slug which must be unique. I think its worth considering the experience here for humans using the system.  The "error" state we're talking about here comes as a result of the author doing something quite interesting. They are looking to write a how-to document which has a similar title to another existing document. 🤯

I believe that there are two things which need to happen here:

**1. Decouple Human generated titles from unique identifiers required by machines**

The software should _silently_ generate a unique slug if a collision is identified. The fact that our software chooses to derive unique identifiers from a field controlled by humans is something we should address and not burden our community authors with.

Perhaps we can signpost what we are doing in the UI. The attached example shows an instance where we reach the collision state, instead of returning an error the application appends a random number to the URL. 

![Screenshot 2023-09-10 at 11 05 42](https://github.com/ONEARMY/community-platform/assets/472589/d19485f9-8ae7-4755-aea7-76d93d7d9010)

Note: a future iteration of the system may allow users to directly edit URLs but is definitely **not** in scope for this bug fix.

**2. Let the human know they are creating duplicate content**

Fundamentally the software is trying to support humans in creating a comprehensive and valuable knowledge base. If we have a situation where there are two titles which overlap we should let the author know so they can adjust their content accordingly.

![Screenshot 2023-09-10 at 11 18 09](https://github.com/ONEARMY/community-platform/assets/472589/0c8e0d94-ba0b-45a3-9a0f-64992b1e68ee)

I do not see this second "nudge" message as being required to mark this bug as solved, instead I see it as a nice to have.

**Comment by goratt12** [comment]
Hi @thisislawatts , thanks for your kind comment!
Regarding the first point, I totally agree.
I think we should use a combination of id (unique) and slug (human friendly) as shown in Stack Overflow's question URL:
https://stackoverflow.com/questions/6815903/what-is-the-correct-way-of-code-comments-in-javascript
https://{domain}/{component}/{id}/{slug}

Regarding the second point, I think it would be nice to show this message when writing the article (validate on un-focus)
and allow the user to create this article as shown in my first point.

Your thoughts about it?

and would you like me to develop the solution? because I saw you self-assigned the PR

**Comment by thisislawatts** [comment]
@goratt12, apologies for the confusion. I assigned the PR as a signal to the other maintainers that I would be the one reviewing this PR. 🤦🏻 

We should avoid introducing another level to the URL hierarchy which break consistency with existing how-to content. 

How about creating a slug that consists of the human generated title combined with a random string, for example if the title is "My First How-to", the slug would be "my-first-how-to-v713bu"

Adopting something like https://zelark.github.io/nano-id-cc/ to generate the random string.

I do not think we should include the ID in the slug, this identifier is _only_ for internal use. Leaking it into the slug runs the risk of someone building something which becomes dependent on it.

**Comment by goratt12** [comment]
I can do that.
I think we should use only numbers in the postfix id,
because the probability of duplicate slugs is so low (a user needs to create a HowTo with the same title)
if we use a postfix of 5 numbers, there will be 100,000 unique postfixes.

**Comment by thisislawatts** [comment]
Sure thing, no strong opinion from my side on numbers Vs numbers and letters

**Comment by evakill** [comment]
@thisislawatts agree with your [proposed solution](https://github.com/ONEARMY/community-platform/issues/2744#issuecomment-1712763587), thanks for putting thought into this! i wanted to loop in @davehakkens here because it seems like this route would break existing links, and this is something we've been sensitive to in the past. is this still something we should consider here?

**Comment by davehakkens** [comment]
thanks for asking @evakill. Which links would it break? Since Luke says "I do not think we should include the ID in the slug, this identifier is only for internal use. "

**Comment by evakill** [comment]
> I do not think we should include the ID in the slug, this identifier is only for internal use. 

i think luke was referring to the database ID. we'd generate a random id for the slug - using the example from above, if you create a how to with the title "My first how to", the slug would be something like "my-first-how-to-v713bu", instead of "my-first-how-to" which is how we currently do it. we would add the id "v713bu" on the backend. then i could create another how to titled "My first how to", but mine would have a slug like "my-first-how-to-f82ba6" so they wouldn't conflict.

thinking more though, i was incorrect thinking this might break existing links because the change would only impact future slugs. there may be some cases where this has already occurred, but maybe better to resolve those separately. 

does that seem right to you @davehakkens @thisislawatts?

**Comment by davehakkens** [comment]
thanks for explaining. Sounds logical to me. Still dont see which links would break. But if the old urls like `my-first-how-to` would stay accessible or be redirected to the new structure  like `my-first-how-to-f82ba6`  (which i think it does due to this PR https://github.com/ONEARMY/community-platform/pull/2279) it works for me!

**Comment by goratt12** [comment]
Added the logic that check if a slug is in use, and if so it generate a random 5 digit number to follow the slug
+
This notice is now showing when a user is using a title that is already in use (Checked onBlur)
![image](https://github.com/ONEARMY/community-platform/assets/23094928/c8932518-7a76-4b23-abd7-94f6c4f33a3a)

**Comment by goratt12** [comment]
Just need to add validation that title hasn't changed so the slug won't regenerate random id.

**Comment by goratt12** [comment]
Added functionality that check if the slug is in use and add 5 random digits to it if is duplicate (Check on submit/draft)
The slug will not change if the title has not changed (will not regenerate slug postfix)
+ 
If a user is trying to use a duplicate title/slug, a notice message will appear (Checked onBlur):
![268099864-9ad0c21e-1a38-4d9f-bc6b-dcacfebdb33e](https://github.com/ONEARMY/community-platform/assets/23094928/548ea5a4-d87c-4068-a228-94f876358748)
