### ISSUE TITLE
[feature request] more information in Follower notifications

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2922]
**Is your feature request related to a problem? Please describe.**
The notification "$person posted an update on a research you follow" is annoying because it lacks information about which specific research the update pertains to. Additionally, it sends a new notification for an edit made very shortly after the initial message, which can be confusing.

![Screenshot_from_2023-10-18_20-26-55](https://github.com/ONEARMY/community-platform/assets/472589/9810051f-2e23-460d-b6ed-f28df2e0889a)

**Describe the solution you'd like**
I would like the notification message to specify the research topic that the person has posted an update to. This will help users quickly identify the relevance of the update without needing to dig deeper.

**Additional context**
Being informed about research updates is useful, but it's equally important to immediately understand the context of these updates. Enhancing the clarity of notifications can lead to a more user-friendly experience.

**Comment by davehakkens** [comment]
Agree! 
But it goes beyond the "follow" update. The same goes for"

- Being mentioned
- Someone useful your content
- Receive a comment

<img width="256" alt="afbeelding" src="https://github.com/ONEARMY/community-platform/assets/13672737/ddfae850-9586-4490-b78e-3c04f5922754">

All notifications are very short and abstract. (due to limited space available in the modal)
Might need a redesign of the popup-modal or have a specific notification page so there is more space available to add extra information?

**Comment by emmapeel2** [comment]
Some suggestions:

- I think the title of the research is better than the word 'research' and it will not be so much additional space. Same with the  other notifications.
- Maybe the notifications can be grouped by Research and then you only need the title once. 
- More information could also be given on hover. For example, the time of the event (I like when they are '5 minutes ago' or 'last year' instead of the actual date)
- In some other platforms, when there is big variation on the amount of notifications received, you have a link to see all your received notifications, and they have more information on each one.
- Also, maybe if you click on an item it should move down the list, or dissapear. This way, when you click on one research, all the edits from that research can get out of the list, as you have already read that.
- The notification 'New comment on your research' should open in the actual comment, not at the start of the research page.

**Comment by davehakkens** [comment]
Continued thinking on this. Putting this here for visibility and marked the issue as "under discussion"
Probably need a seperate issue at some point when things are defined. 

### Notifcations Research

| Type |  Now | Next (suggestion) |
| -------------| ------------- | ------------- |
|Comment | New comment on your research by [username](link-to-username.com) | New Comment from [username](link-to-username.com) on your research [insert content title](link-to-content-com)  |
|Useful | Yay, [username](link-to-username.com) found your research useful | Yay, [username](link-to-username.com) found [insert content title](link-to-content-com)  useful  |
|Follow | Username posted an update to this research you follow |  username posted an update to the research [insert content title](link-to-content-com) you follow|
|Mention | [Username](link-to-username.com) mentioned you in this research | [Username](link-to-username.com) mentioned you in this research [insert content title](link-to-content-com) |
|Moderation | Your [Research](link-to-content-com) has been approved | Your research [insert content title](link-to-content-com)  has been approved |

### Notifcations How-to
| Type| Now | Next (suggestion) |
| -------------| ------------- | ------------- |
|Comment | New comment on your how-to by [username](link-to-username.com) | New Comment from [username](link-to-username.com) on your how-to [insert content title](link-to-content-com)   |
|Useful | Yay, [username](link-to-username.com) found your how-to useful | Yay, [username](link-to-username.com) found [insert content title](link-to-content-com)  useful  |
|Mention | [Username](link-to-username.com) mentioned you in this how-to | [Username](link-to-username.com) mentioned you in this how-to [insert content title](link-to-content-com) |
|Moderation | Your [How-to](link-to-content-com) has been approved | Your How-to [insert content title](link-to-content-com) has been approved |

### Other Future Notifications to define
We have two more notifications types coming up in the near future
1. Nested comments. This could have a specific notifications, example: Username replied to your comment
2. Questions module. This will have a few different notifications, similar to research. Types:  useful, comment, follow etc.


Let me know if anyone has any suggestions on the copy for the text

**Comment by mariacastiel** [comment]
Some suggestions:

- If it does not fit, add more information on hover. 
- At the end of the notifications, a page where to go and see all the notifications, in case there is more than 5. Also keep the old notifications.
- Date of the notification (better if it is on the format "yesterday|6 months ago|just now")
- When somebody answered your comment, go to that comment and not to the start of the research module.
