### ISSUE TITLE
[QuestionListing] Search

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2969]
It should be possible for someone to search the Question listings for items which match based on the contents of the Question title or description.

Look at the implementation for the how to listing for reference.

**Comment by osrplastic** [comment]
@thisislawatts , @evakill , @davehakkens, @katharinaelleke, @chrisclarke  ....

I am impressed by the ignorance & arrogance you've been wasting everyone's time & resources reinventing the wheel. Search, CMS, directories, ... how many times you want to reimplement this ? The planet is on fire, the project & it's people left with no prospect, losing their savings, invests, ... and you, cashing in with all the dirty tricks, .... 

I am watching this miserable example of incompetence & selfishness now since 6 years, and you keep surprising me. None of the designs or the tech meet any of your communicated expectations. If there's any decency & dignity left in you, please resign, apologize, and finally f*** off! Everytime your generous interference did cost the project & folks jobs, innovation, surface, ... 

600+ pins censored, tens of thousands 'community members', sitting in a clowncar, 27 verified, the HQ struggling to pay bazar fees 5M in losses, 10m in damages, ... what the fu** is wrong with you !? I understand, you, the 'management', featured bazar sellers as gestapo, deciding who speaks to who, ... entirely lost touch with ground - 

but you, the so called developers, you should have know better - again giant clusterfuck, of no use to anyone. 

enjoy your self, on the back of others

polite as usual, another sheep you just screwed, a**holes !

**Comment by bn01032** [comment]
@thisislawatts , @evakill , @davehakkens, @katharinaelleke, @chrisclarke ....

how long we have to watch this anyway ? you missed everything about plastic recycling, the craft, the people, the trade, development, modern communication, trade, .... and now this ... !

banning, defamation, baiting / tricking the youth, bullying, hit & run, manipulation, all the bullshit theatre is biting back since years, and you, spoiled little kids keep jerking as nothing happened. 

not surprised you have clowns as Mattia, ...

careful ! watch the trends, the data, the dev - one millimeter more and you're f*** out forever !

g

**Comment by bn01032** [comment]
in the meantime, the best of the best, keep moving, without you, as always

![image](https://github.com/ONEARMY/community-platform/assets/149538505/03f7047c-e81d-4aa7-a3d1-0b5f592397df)

in all that years, you still dare to come up with more bullshit, as usual, on the back of others.

**Comment by bn01032** [comment]
teens, women, elderly, contributors, - you dear Mafia, you better keep walking with the back to the wall !

**Comment by bn01032** [comment]
last not but least, did you even consider the best or other options, for your so called 'beloved' community, 'the family' ? 

since you're new to all this, ... if you need hand, a copy, ... you let us know :))

perhaps you get your homework right one day, at least something

**Comment by davehakkens** [comment]
Image as reference 
![search](https://github.com/ONEARMY/community-platform/assets/13672737/ee02afa4-9e26-4e79-9d31-d22865660309)

**Comment by sanjanaj2** [comment]
Hi, I wanted to work on this issue. 
I was wondering if I needed to do anything do except comment?

**Comment by davehakkens** [comment]
nice, go for it! 
The moment you submit a PR (can be draft) we will assign the issue to you
