### ISSUE TITLE
Focus alignment 

### ISSUE THREAD

**Issue by thisismattia** [ONEARMY/community-platform#2993]
Hey everyone 🔆

I believe the badges should all be on the same line and not breaking on the next line. 
<img width="855" alt="image" src="https://github.com/ONEARMY/community-platform/assets/17761877/d10f3510-d539-4eed-9a04-b4d9c65c1807">

Is there any chance to force them all in the same line maybe making them a little smaller or something?

**Comment by zweertsk** [comment]
Hi, I'm new as an aspiring contributor, so not really known in this project (yet!). Im building the project locally as I type this.
A question I have about this ticket is about the responsive design for the app. I can imagine that if a mobile user is on this page and the images shrink into molecular sizes, to display them side by side because of the screen size, the experience is not very good. So, yes I think this request can be implemented up to a certain screen size. Below that size, different styling is applied.
