### ISSUE TITLE
[bug] Letter "e" allowed on Impact feature

### ISSUE THREAD

**Issue by m-azoubel** [ONEARMY/community-platform#3292]
**Describe the bug**
Letter "e" allowed on Impact feature

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'Settings'
2. Scroll down to 'Positive impact'
3. Click on 'Expand and edit'
4. Click on 'Edit data'
5. Add letter 'e' to any data
6. See error

**Expected behaviour**
Only numbers should be allowed

**Screenshots**
![image](https://github.com/ONEARMY/community-platform/assets/90778074/bdddb140-82e0-44e9-91a4-7cdd40d23ee3)

**Comment by manacespereira** [comment]
one question... how can i have access to this screen... which access should I use locally in order to be able to see those features? I could work on it too and fix real quick

**Comment by m-azoubel** [comment]
hey! you should log in your community platform account https://community.preciousplastic.com/

**Comment by manacespereira** [comment]
yes. just did it. but i cannot see  the `Positive Impact` area :)

**Comment by m-azoubel** [comment]
@benfurber maybe do you know why this is happening?

**Comment by manacespereira** [comment]
@m-azoubel @benfurber i might need some permissions... if anything, can you give those permissions for running locally only?? I can fix all these little defects real quick...

**Comment by benfurber** [comment]
@manacespereira You can get to the edit impact components (which you need for your other PR too) but having a workspace account type (that's any account type that's not a member account).

**Comment by manacespereira** [comment]
> @manacespereira You can get to the edit impact components (which you need for your other PR too) but having a workspace account type (that's any account type that's not a member account).

sure. can u tell me how can I have these account information?

**Comment by benfurber** [comment]
You're able to select it yourself from the settings page.

**Comment by pizzaisdavid** [comment]
In order to be able to reproduce this on local development, you must also explicitly click "Theme" and select "Precious Plastic" in the red banner and then refresh. (And then switch to a workspace profile.)

Gif demo:
![capture](https://github.com/ONEARMY/community-platform/assets/4391884/dabc3bad-a2df-401f-891b-6584cc863298)

Why is that needed? Because this is only for Precious Plastic, and when in local development there is a check for a string stored in local storage.
```
localStorage.getItem('platformTheme') === 'precious-plastic'
```

**Comment by goratt12** [comment]
This issue occurs because of how the browser treat the `<input type="number"/>` field.
As stated in the official html specs, this input should accept any [Floating-point numbers](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#valid-floating-point-number)

> A floating-point number consists of the following parts, in exactly
> the following order:
>     
> 1. Optionally, the first character may be a "-" character.
> 2. One or more characters in the range "0—9".
> 3. Optionally, the following parts, in exactly the following order:
>     1. a "." character
>     2. one or more characters in the range "0—9"
> 4. Optionally, the following parts, in exactly the following order:
>     _**1. a "e" character or "E" character**_
>     2. optionally, a "-" character or "+" character
>     3. One or more characters in the range "0—9".

We can prevent this from happening if we add the `onKeyDown` prop to `ImpactQuestionField`:
```
<Field
    component={FieldInput}
    data-cy={`${formId}-field-${field.id}-value`}
    name={`${field.id}.value`}
    sx={{ background: 'white' }}
    type="number"
    onKeyDown={(event) => {
        if (event.keyCode == 69) event.preventDefault()
    }}
/>
```

I would like to hear what the maintainers think about this solution

**Comment by goratt12** [comment]
We can even prevent all non-integer characters and keep only `[0-9\.]` (1 to 9 and dot).

**Comment by mariojsnunes** [comment]
> We can even prevent all non-integer characters and keep only `[0-9\.]` (1 to 9 and dot).

Some languages use comma instead of dot.
Also, instead of using a keyCode this would be more readable:
https://stackoverflow.com/a/58097342
