### ISSUE TITLE
[bug] Actually limit tags to four

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3347]
**Describe the bug**
Research, how-tos and questions all use the `TagsSelectField` component which says only four tags should be allowed...but, eeerrr, it doesn't actually limit it to four

<img width="524" alt="Screenshot 2024-03-14 at 13 41 31" src="https://github.com/ONEARMY/community-platform/assets/16688508/a53b78df-6ebe-445e-9b33-aa5bf8980c6f">

**Expected behaviour**
Using `react-final-form`'s validation behaviour and the existing error handling approaches, please fix this!

**Comment by simontree** [comment]
Hey @benfurber, this could be my first issue - but I think I have a working idea already - just need finetune the styling. Do you need to assign me? Best wishes

**Comment by benfurber** [comment]
That's great, thanks @simontree - it's yours!

**Comment by V24039** [comment]
Hi @benfurber I would take up this issue if it is still open

**Comment by benfurber** [comment]
Thanks @V24039. Please do!

**Comment by V24039** [comment]
@benfurber thank you for assigning it to will try to complete it ASAP

**Comment by V24039** [comment]
@benfurber After analysis I think the validations can added only at the page level (validation for each page which uses the tags), because the tag is developed as a custom component like text field so adding validation at the component will not restrict the user to submit.
Will be waiting for your analysis and reply to move forward
