### ISSUE TITLE
[bug] Make how-to header image full height

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#3407]
**Describe the bug**
The first how-to image should be full height of the div.
This layout got broken a while ago

**See it on live **
Visit a how-to ([example](https://community.preciousplastic.com/how-to/set-up-a-machine-shop))

**Expected behaviour**
This is what it should look like
![before-after](https://github.com/ONEARMY/community-platform/assets/13672737/7a96fa97-18ee-4014-9ba5-4ec4b4e8e2a2)

**Comment by phlapjack** [comment]
Hi @davehakkens ! Newbie here, I'd like to work on this as my first PR.

**Comment by phlapjack** [comment]
Seems this has already been fixed with the `height: 100%` style (line 390) in `HowtoDescription.tsx`, added in commit: 6025e121c9d926d15a561815c0a810363c983fb5
See local testing: 
**with.png (height: 100% style)**
![with](https://github.com/ONEARMY/community-platform/assets/1590042/64d88c3d-5f85-4d6f-ba82-cdfbeeaa64e0)
 **without.png (no height style)**
![without](https://github.com/ONEARMY/community-platform/assets/1590042/62594f94-4398-4a17-89b4-82c86db86ceb)

**Comment by davehakkens** [comment]
Yeh someone tried to fix this before. But it doesnt look fixed on live.. any ideas why?

**Comment by phlapjack** [comment]
The `AspectImage` themeUI component is generating some divs, one of which has a `position: relative` style, if this style is removed it seems to cause the picture to expand to fill it's parent div...
![auto_gen_position_relative](https://github.com/ONEARMY/community-platform/assets/1590042/1f15c722-f3e6-4bae-8d04-62c78f3037d2)

So I feel like there are a few options to explore:
1. Figure out how to not generate those divs from AspectImage
2. Figure out how to have the div generated without the style
3. Re-structure the layout so that the style of the generated div doesn't matter
4. ?

**Comment by benfurber** [comment]
Hey @phlapjack. Strongly agree with removing any position relatives you find in the way.

**Comment by benfurber** [comment]
@phlapjack I wouldn't worry about that. Just the change you identified for the `HowtoDescription` component will hopefully do the trick. Also in the PR, I'd really appreciate seeing (in screenshots, etc.) this fix working for images that are bigger/small than the content on the left hand side and what very portrait and very landscape images look like in that space.

**Comment by phlapjack** [comment]
thanks @benfurber ! The problem I have, is that the offending `postion: relative` is in a div that is auto-generated by the AspectImage component. So far I haven't found a way to keep AspectImage from generating the div, or a way to style the generated div differently.
I messed around with using a plain old img tag, but that probably isn't the correct way to go. Another thought was to extend the AspectImage component and alter it's behavior to not generate the div (or generate with a different styling), but that's not something I know how to do yet...
Maybe there's another component for images that could be used...I'm coming at this as a React newbie though so it's a slow process...

**Comment by benfurber** [comment]
@phlapjack So it's not the `position: 'relative'` I can see on line 349 of `src/pages/Howto/Content/Howto/HowtoDescription`?

I can also see from line 348 of that file that we're doing some manual width sizing when we should be using flex to deal with all that.

**Comment by phlapjack** [comment]
@benfurber so far looks good except there is a question about very portrait pictures, should they be able to expand the box as far down the page as the image is tall ? I would guess not, but what would be expected behavior here ?
![page_with_very_portrait](https://github.com/ONEARMY/community-platform/assets/1590042/d97109b3-ba37-4dcb-ba79-ef3d8ee978b9)

**Comment by benfurber** [comment]
> @benfurber so far looks good except there is a question about 'very portrait' pictures, should they be able to expand the box as far down the page as the image is tall ? I would guess not, but what would be expected behavior here ? ![page_with_very_portrait](https://private-user-images.githubusercontent.com/1590042/319973650-d97109b3-ba37-4dcb-ba79-ef3d8ee978b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzOTU1NjIsIm5iZiI6MTcxMjM5NTI2MiwicGF0aCI6Ii8xNTkwMDQyLzMxOTk3MzY1MC1kOTcxMDliMy1iYTM3LTRkY2ItYmE3OS1lZjNkOGVlOTc4YjkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDZUMDkyMTAyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWFhZmMyZTdiMDM0ODlhYmUxZTNiZmI3ZDViNDJlMTk3N2I5MDU5NjcyMjFmZGU0NTgzYzhlNGVmZTNhODc3ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.LDDNamQZlelPW2SHysjkk_CO5-u7H-rjitaVOM6UCUI)

Not sure I have a preference. @davehakkens?

**Comment by davehakkens** [comment]
Ideally the height of the header-div is defined by the text and components on the left div.
The div on the right side uses its space for an full image.

If the aspect ratio of the image doesnt match the div it would be display with something like `object-fit: cover;`

**Comment by phlapjack** [comment]
ok thanks @benfurber  and @davehakkens , I'll make these changes and post pics of the testing results here and also I'll push a PR.
