### ISSUE TITLE
[bug] Tests failing due to calling firebase auth

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3414]
**Describe the bug**

Got this error when cypress tests ran:
"Firebase: Access to this account has been temporarily disabled due to many failed login attempts. You can immediately restore it by resetting your password or you can try again later. (auth/too-many-requests)."

[Settings][All account types[Can update username and password]

**Expected behaviour**
Firebase calls should be mocked.

**Comment by benfurber** [comment]
[Due to this test of mine](https://cloud.cypress.io/projects/4s5zgo/runs/5363/test-results/1e99f4f3-2078-4718-b3f3-f54da1db74a2?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D&utm_source=github).

I'll try to fix it now.
