### ISSUE TITLE
[Flaky Tests] Investigate and fix it

### ISSUE THREAD

**Issue by tuliobluz** [ONEARMY/community-platform#3477]
**Is your feature request related to a problem? Please describe.**

Currently, we have 1 High and 3 Medium flaky tests, as shown below. The idea of this issue is to investigate and fix them.

![Flaky](https://github.com/ONEARMY/community-platform/assets/21323883/04d7a27d-1a89-4184-8875-e16ce0ed7b0a)

High:

[Can contact profiles by default] 

`> KeyPath email on object store 2tn1X_messages_rev20231022 is not indexed`

Medium:

[By Authenticated]
`Timed out retrying after 15000ms: Expected to find element: [data-cy=intro-title], but never found it.`

`> Cannot read properties of undefined (reading 'updateAggregation')`

`$el.css is not a function`

[by default should render all `accepted` pins]

`Timed out retrying after 15000ms: Expected to find element: [class*="leaflet-marker-icon"], but never found it.`

`Cannot read properties of undefined (reading 'updateAggregation')`

[Warning on leaving page] 

`Timed out retrying after 15000ms: Expected to find element: [data-cy=intro-title], but never found it.`

`Timed out retrying after 15000ms: expected 'http://localhost:3456/how-to?sort=Newest' to match /\/how-to$/`

**Describe the solution you'd like**

First, investigate and come up with a solution for the flaky test.

**Describe alternatives you've considered**

Check the logs and based on it, act to fix the issues.

**Comment by thisislawatts** [comment]
Sharing here for visibility this commit, https://github.com/ONEARMY/community-platform/pull/3494/commits/da9c59dff0f0c5ad34cc7f88d1bec1f3d1dd3060, which skips 2 tests in our e2e suite due to issues with appear caused by state in the underlying user account. 

We have **way**  too many tests tied to this user account, ideally we can find a path forward here where we isolate user accounts to a single test suite.
