### ISSUE TITLE
[e2e] cypress approach to seed test data

### ISSUE THREAD

**Issue by tuliobluz** [ONEARMY/community-platform#3601]
**Is your feature request related to a problem? Please describe.**

The app requires indexes to show, filter, and search lists of docs. When the app is deployed these index rules are generated for the named document collections.

@benfurber has pointed out that there is a problem with Cypress setting up a new document collection for each run. This is causing some failures and flaky test for e2e tests.

It was decided that the **question feature** would be the starting point as it is a small and simple feature.

**Describe the solution you'd like**

1. Create a new job to seed the test data before the e2e test run
2. As the test data will be set up only once, adapt the e2e scripts to continue passing

With this solution, cypress will not set up a new collection every run.

**Comment by benfurber** [comment]
Thanks @tuliobluz. 

1. As you rightly pointed out to me on discord, there's probably no need to seed the collections at all. The tests for 'read' of documents should assume the documents are present already. Obvs potentially creates other issues, but less likely ones that bugs/regressions happening from every day engineering.
2. So for this it's probably about excluding questions from the seedDB command in `packages/cypress/src/support/db/firebase.ts`
3. What I'm not sure about from a quick scan of the code is how the `DB_PREFIX` flows through to what collections the cypress instance of the app calls.

**Comment by tuliobluz** [comment]
Excluding the question from the seed we need to provide the data for the read test. 

Can we start a populated database with the test data?

Or

Can we seed the database during the start-up of the app with all the test data with the same index rules?

**Comment by pizzaisdavid** [comment]
The ticket isn't super clear for me, I think I don't fully understand what a "job" is:

> Create a new job to seed the test data before the e2e test run

And what a "run" refers to (running a single test or all the tests?)

> With this solution, cypress will not set up a new collection every run.

But, to me, the ideal maintainable/understandable approach from a developer point-of-view would probably be:

Before each test, the database is wiped clean. At the start of a test, if pre-existing data is required, then it is ceated via hard coded API calls. Then the part that we actually want to test would be done via interacting with the web application like a normal user. A e2e could have multiple steps but each test would be independent from each other.

So for example, the test case is "should post answer to question":
- Before test: database is wiped
- Setup section of test: create user account, post question, create a second account.
- Main part of test: login to second account, navigate to question, submit answer.
- Validate answer was posted, either via user interface or more API calls.

I don't know how Firebase works very well, so maybe making API calls in Cypress to submit data is difficult? Not sure if the caching would be solved or not with this.

Because I didn't totally understand the previous messages, maybe this is more-or-less the idea proposed?

**Comment by benfurber** [comment]
@tuliobluz - @pizzaisdavid is right that the context to this challenge isn't provided. If you copy over, and possibly rephrase in your own words, my original brief to you from discord on May 24th, it'll give David more context as to why the work is needed.

**Comment by tuliobluz** [comment]
I am sorry that I had a poor description. I created this issue to discuss the best approach that we should use.

**Context from discord:** 

What we discussed on Discord was that currently, cypress tests set up temporary document collections with random IDs (e.g., <random id>research<etc.>) during each test execution. This approach prevents tests from utilizing existing document collections and their associated indexes.

One of the possible short-term solutions is the Cypress tests use existing document collections within the deployed application.

A potentially long-term solution is mocking the API.

**Issue description**

When I wrote this ticket I described a solution I had in mind, but the same one will lead to the current problem.

A brief explanation about what I mean with **job** will be stage/script that runs before running the test scenarios

**Current issue goal**

Discuss possible solutions to cypress tests using the existing document collections.(from this issue if we decide to change anything we can create a fresh issue to describe and clear a bit)

**My 50 cent**

I agree with @pizzaisdavid regarding the e2e and steps(tests should be independent of each other), this is one of the approaches, and cypress is using it now.

The one that might help fix this issue is to start up the database already populated with the test data, then Cypress will not need to set up a temporary collection.

- Before all tests not related to cypress running: the database is populated with test data.
- Setup section of test: create user account, post question, create a second account.
- Main section of test: login to second account, navigate to question, submit answer.
- Assert section of test: validate answer was posted, either via user interface or more API calls.

The tests will remain independent because the data is already set up, we will need to adjust the scripts.
