### ISSUE TITLE
[feature request] Improve CreateComment and CreateReply components

### ISSUE THREAD

**Issue by dalibormrska** [ONEARMY/community-platform#3656]
> This ticket is part of series of 7 tickets concluding a design task focusing on improving design and usability of comments feature. Here you can find the [Figma file](https://www.figma.com/board/GfQPMs7PyC7jbkymDTco2D/CP-%2F-Nested-Comments-Improvements?node-id=0-1&t=7sgMA4ZPYXAMb03A-1) for more context.

### **7/7 - Improve CreateComment and CreateReply components**
---

**Is your feature request related to a problem? Please describe.**
The component is currently taking a lot of vertical space, since the button is below. The button is also too big visually on mobile. The textarea is not increasing the height automatically, so the user has to drag the bottom-right corner to re-size it. Additionally, its default height is too big for the text size and is making the text not centered. 

<img width="823" alt="image" src="https://github.com/ONEARMY/community-platform/assets/35503298/3a0e13b6-f584-4b33-bb3a-2f7a283ef614">

**Describe the solution you'd like**
[Figma link](https://www.figma.com/design/x4DcaUjwiigjCySAt5omxB/CP-%2F-Signup%2C-Settings-and-Gatekeeping?node-id=543-14229&t=8B7R1EvPTUd7KZSh-4) to the file where you can see the measurements. Click on the element and hold option mac key to see the measurements.

![image](https://github.com/ONEARMY/community-platform/assets/35503298/7343aa17-0d95-4405-a621-f9dc78621f1f)

> Ticket scope to include (notes from Ben):
> 
> 1. Update button component to choose to hide text on mobile viewpoint. 
> 2. Changing our textarea component (and implement for all instances) to include the character limit count.
> - Questions - title, description
> - how-to - title - Short description
> - how-to steps - title, description
> - research - title, description
> - research update - title, description
> - settings - Tell us a bit about yourself, Short description of your pin
> - Error handling
> - Rules around colours to use? e.g. red for under/near limit?

**Describe alternatives you've considered**
I think there are simpler alternatives, just changing the flex-direction so that the textarea and the button are next to each other, but I think this component deserves some love and nice styling. <3

**Additional context**
See the milestone

**Comment by elideg** [comment]
@dalibormrska I can take this ticket on, do you mind assigning it to me?

**Comment by tomgiagtz** [comment]
Hey there! Any chance I could have this assigned to me? I should be able to get this done next week :)

**Comment by benfurber** [comment]
@tomgiagtz Welcome! Good luck. Please shout if you have any questions/issues.

**Comment by tomgiagtz** [comment]
Okay I made some progress yesterday and today, here it is so far!

<img width="1452" alt="image" src="https://github.com/user-attachments/assets/d9714c00-5009-4ea0-b46c-d1d50ec970e1">

<img width="1448" alt="image" src="https://github.com/user-attachments/assets/e8c57dfc-fa78-4061-a3cf-49fc15d1b7a4">

<img width="1447" alt="image" src="https://github.com/user-attachments/assets/30ab7453-be92-4e88-876a-2a47d0905d5c">

I'm waiting to get the character count placed just right because...

I have 2 sticking points right now:

### 1- Auto Sizing 
Auto Sizing the text area is fairly difficult it seems, especially with the intended functionality of expanding to a max size limit.

I found some discussion online, most people recommended using a package 👎 , but I found [this method using the useEffect hook](https://stackoverflow.com/a/60795884). I figure this is the best way to go as it will be easier to tie into theming but I wanted to bring it up incase I missed something pre-existing in the project. Based on the widespread use of `<Textarea/>`, I'm thinking this deserves it's own component, let me know what you think.

### 2- Mobile Detection
I haven't looked through much of the existing codebase yet, but in order to implement the Mobile v2 design, I believe I will need some sort of `isMobile` boolean to be able to conditionally render the image, and remove the arrow and profile picture. 


I see the profile image is already disappearing on smaller screen sizes, but based on the code in MemberBadge.tsx, I'm not sure that's intentional? Best guess is there isn't a low detail version of the default prof picture... This is what I'm seeing on smaller mobile sizes.
<img width="562" alt="image" src="https://github.com/user-attachments/assets/3135e1d9-2caa-41b2-816e-a76f9422beb9">

Is there some existing example of what I should do for this? Do I need to figure out how to get a media query to cover this functionality? Let me know! 

Thanks, Tom

**Comment by benfurber** [comment]
Awesome, thanks @tomgiagtz. Likes like you're making great progress.

On one, sounds like some great investigation. The suggestion of useEffect is a good one and definiting of moving as much as you can to do the component library (`packages/components`).

For the mobile stuff, I try to use the [responsive element of sx](https://theme-ui.com/sx-prop) to do that whereever possible. Basically whenever you see an array for a style element that's doing the responsive hard work. e.g. when you see something like: 
```
padding: [1, 2, 3, 4],
```
That's setting a different padding across our four viewports. 

I try to default to using that, even when there's enough complexity to justify doing entirely different mobile/desktop implementations [like I did recently here](https://github.com/benfurber/community-platform/blob/2d3b787e98a7a9a277b5d2bdd6198d860cadde4b/src/pages/Maps/Content/MapView/MapWithList.tsx).


Does all that make sense?

**Comment by benfurber** [comment]
Hey @tomgiagtz, how are you getting on?

**Comment by johannes-ross** [comment]
I'd like to work on this one :)

**Comment by dalibormrska** [comment]
@benfurber 

> I'd like to work on this one :)

**Comment by dalibormrska** [comment]
@benfurber 

I did the assignation, I hope it's okay.

Have fun Johannes! :))
