### ISSUE TITLE
[bug] Research article's total comments count is reset to 0 after being set to Draft or Republished

### ISSUE THREAD

**Issue by onim-at** [ONEARMY/community-platform#3905]
**Describe the bug**
Editing or setting as draft a research reset its total comments count to 0

Example of this issue on on PRD:
[Should we get a tractor or digger to work on the land?](https://community.projectkamp.com/research/should-we-get-a-tractor-or-digger-to-work-on-the-land)

**To Reproduce**

- create a research
- create an update
- add comments to update -> the comments total count is correctly updated
- set the research as draft or publish it again -> the comments total count is set to 0

**Expected behaviour**
The research article's total comment count should not be reset

**Screenshots**
![image](https://github.com/user-attachments/assets/052bd266-c88e-4e8a-a50c-37719e45f4e3)

**Comment by davehakkens** [comment]
is this the same problem as how-to?
As some of them also have 0 comments (but actually 25)
https://community.preciousplastic.com/how-to/shredder-21
![image](https://github.com/user-attachments/assets/3be26fa0-443a-4ffd-bbec-2a6fbc119b01)

**Comment by onim-at** [comment]
From what I can see, the HowTo page manually counts the number of non deleted comments, that's why the correct amount is displayed
![image](https://github.com/user-attachments/assets/db2300fe-fc37-4b76-b2a2-520484ebaf1a)

The HowTo card relies instead on the `howTo.totalComments`
I played a bit with the UI but didn't manage to reproduce this other issue yet

**Comment by pizzaisdavid** [comment]
I re-read the thread again, and you might have already figured out what I said, as you mention card.

If the card relies on a number that gets manipulated instead of actually counting, it is possible the bug was already fixed, but this could just be left over as maybe no one wrote a script to fix the stuff. Depending on how the logic works for counting the comments, adding a new comment might just fix it.

I left a comment on it, and then deleted it. It re-synced.
![image](https://github.com/user-attachments/assets/4a7c192b-a97b-45ce-93b3-f7037824fb86)

Of course, if the bug wasnt actually fixed, maybe in the future it will get un-synced again.

**Comment by davehakkens** [comment]
nice discovery @pizzaisdavid, hopefully that does the trick
