### ISSUE TITLE
[Tech] Render Terms page server-side

### ISSUE THREAD

**Issue by mariojsnunes** [ONEARMY/community-platform#3934]
**Is your feature request related to a problem? Please describe.**
Server-side render the Terms page.
This will lead to removing prerender.io as a dependency and cut costs.

**Additional context**
This is part of the effort to decouple the firebase from the client to make it easier for a Supabase migration.
And also improve codebase maintainability.

**Comment by onim-at** [comment]
Hello! I'd like to help with this issue but need an advice on how to proceed
From my understanding, the SSR can be enabled by removing the `clientLoader` function from `_.terms.tsx`, however this will trigger an error due to the `SeoTagsUpdateComponent`
Can I remove that component from `_.terms.tsx` since it will be rendered server side? Is there something else I need to do to avoid a regression?

**Comment by mariojsnunes** [comment]
yes that's correct.
SEO should now be created by Remix's meta function.
example for the howto: https://github.com/ONEARMY/community-platform/blob/916c7f241ce536727a0af5bb7cc92b845d69ed32/src/routes/_.how-to.%24slug._index.tsx#L17-L27

In the case of Terms and Privacy pages, should only need to specify the title.
