### ISSUE TITLE
[discussion] - Ways to ensure content quality

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#532]
**Is your feature request related to a problem? Please describe.**
The system is very open at the moment, before general release we will likely want to put in place some sort of system to help ensure inappropriate content can be quickly removed or put aside, and potentially include ways to promote content which is viewed as more useful by the community.

**Describe the solution you'd like**
Perhaps a simple system to flag inappropriate content for review, and either a rating or up/down vote system to help promote content. Possibilities include reddit-style voting, facebook-style likes, or ebay-style rating based on one or more characteristics.

**Describe alternatives you've considered**
Manual curation and moderation, however this would likely become tedious and could go against some of the more open philosophy of the platform. I would be interested to know other people's thoughts on the roles of moderators vs automation...

**Comment by catx23** [comment]
is this about a forum or articles ? either way; I wrote Adrian a few thoughts and in the last 30 years i haven't seen better than Stackoverflow. Simplest and more fitted model I see at the moment is : 
1. turn conversations in to content : more difficult and needs community help; 
2. turn content into conversations : easy and would to funnel new findings, ideas, etc.. into the right place; that assumes a good search system (as on SO) which suggests users already existing questions. to, publiclab.org (different discussions on articles) is doing this quite right and evtl. you have a look at it because it seems a quite few years ahead of one-army. we pre-release a new module in  Sept. called 'PP Search' which searches the forum and other sources; I can leave you a react compatible search box with an auto-suggestion implementation of your choice. 

other than that; forum software typically provides split, flag, merge - actions for posts. in the case of PP I'd possibly also add 'private' (sensitive) and 'meta' (collab work) at some point.

**Comment by catx23** [comment]
publiclab.org also has 'templates' for posts/articles btw. that also helps a lot to ensure some policies for content.

**Comment by chrismclarke** [comment]
Thanks for all the advice @catx23 !

In the first case we are talking more about articles, such as the 'how-to' guides that people can create. These are built on top of our own custom system, so whilst less susceptible to the likes of robo spam, we need to develop our own custom means of moderation for contributors. Currently anyone can write a how-to and it appears immediately at the top for the world to see - clearly this isn't a very good way to go about things. A few options could include:

1. Force all content to be approved but some sort of admin before going live
2. Allow users to quickly flag content that might not be suitable for whatever reason for review
3. Allow users to promote/demote content via some sort of voting/rating system
4. Restrict who can post content to only those that have passed some sort of approval system 

I personally do like the models on stackoverflow and reddit, and would be most keen on something where less gatekeeping is required, and responsibility is shared more widely. Whether this would work in reality, is anyone's guess.

I like the templates and guidelines suggested, we have that currently and I hope will continue to do so for all new parts of the platform. We don't have a good option at the moment for turning content into conversations, but hopefully use of a 3rd party forum will help to achieve that, and as you said come with its own set of tools.

**Comment by catx23** [comment]
Ok,
in the short term you could : 
- place a guide or an example article (links to supplies write a sort of best practice article, similar to the IOS UX guide lines; basically a collection of dos and don'ts; Since you're on react / material-ui; there is a repo of Microsoft (https://developer.microsoft.com/en-us/fabric/#/controls/web/breadcrumb)
- for the moderating/promoting/demoting/approval part : you could create a simple panel with 'new how-to', 'changes', etc.. and leave the order of articles sorted : ie : by upvotes and/or activities/views first. For multi-dimensional sorting; the filter code I gave you for the discussion list is generic. Possibly I have to add some notes on how to use it.

**Comment by chrismclarke** [comment]
Discussion moved to slack/other general discussions. closing here
