### ISSUE TITLE
Mobile integration of the Header

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#585]
As suggested in the [mockup here](https://one-army-community-platform.webflow.io/), integrate the mobile version of the menu.

eg :
<img width="334" alt="Capture d’écran 2019-09-16 à 19 27 20" src="https://user-images.githubusercontent.com/4993215/64979471-176b4980-d8b8-11e9-8a42-dee6351c0fd8.png">

Note : resize your browser to see the mobile result.

**Comment by catx23** [comment]
it’s amazing with what kind of people we have to deal with, permanent destruction – since June, damages in the thousands – no sorry, no apologize, just some cool insults of Mr Hakkens :

We’ve got possibly 10 times banned, lost all friends and private chats for  :

– asking what to tell this poor people asking about this filament – one of the biggest lies ever of Mr Hakkens
– setting out a bounty to get this 3d printer story going

@davehakkens and the rest of your gang: I don’t know how old your are, but obviously not old to have a little respect or others – who do your work.

Please restore our accounts – we have ongoing activities with others – and NOT WITH YOU !!!
