### ISSUE TITLE
[bug] datepicker doesn't appear in safari

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#629]
**Describe the bug**
When user want to create an event and using safari browser, the datepicker display as a regular input field.

**To Reproduce**
Use safari browser and navigate to `/events/create`.

**Expected behavior**
User should be able to add a date using a datepicker.

**Screenshots**
<img width="540" alt="Capture d’écran 2019-10-08 à 16 10 23" src="https://user-images.githubusercontent.com/4993215/66403199-75d2a600-e9e6-11e9-804b-efb2a5cf3b07.png">

**Additional context**
In codebase, the event form creation is located in `src/pages/Events/Content/EventsCreate/EventsCreate.tsx`

**Comment by lauvrenn** [comment]
It's because Safari unfortunately doesn't support the native datepicker. One way to tackle this would be to attach a jQuery datepicker instead when a browser doesn't support a native one. I saw jQuery, and the required jQuery UI, aren't installed in the project though, @chrismclarke do you think they should be brought in for this one thing? :thinking:  I remember reading that jQuery UI is quite a big library

An alternative to a datepicker would be adding a placeholder; it'd indicate the date format to Safari users while being ignored and not shown by browsers supporting the datepicker

**Comment by chrismclarke** [comment]
Yeah support isn't even on the roadmap it seems:
https://caniuse.com/#feat=input-datetime

I would say not to bring in jquery just for the one feature, as said it is quite heavy and also can have a tendency to interfere with other packages. I would say we should just import a specific lib to use for a date-picker like we do for the select picker. 

https://www.npmjs.com/search?q=react%20date&ranking=popularity
Take your pick :D

**Comment by lauvrenn** [comment]
Yeah, I stared at the roadmap in disbelief when I found out about it :joy: Okay, I went with the most common one, hoping it works :joy:
