### ISSUE TITLE
Cannot log-in when reading a how-to

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#638]
**Describe the bug**
the **Log-in** button didn't work when reading a how-to

**To Reproduce**
ccd2289b1e72b11164d6b5b9686e36f180e1dd40

**Expected behavior**
Take users to the login-page or show a modal to log-in

**Comment by chrismclarke** [comment]
Really like having a bugs section of the ci!
Can see it's a simple mistake of how the sign-in url is populated (adds '/sign-in' to the end of whatever the current page is instead of comparing to the root)
i.e `https://dev.onearmy.world/how-to/sign-in` instead of `https://dev.onearmy.world/sign-in`

Will make a quick fix
