### ISSUE TITLE
Don't show loading... when there is no how-to left

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#639]
**Describe the bug**
**loading...** was always shown even if there was no how-to matching selected tags

**To Reproduce**
fccf3d8ac0d3451a0d35b92e83aa25ca5b4effc9

**Expected behavior**
Should say to users there is no more how-to available
![image](https://user-images.githubusercontent.com/2813016/66543104-a0476f00-eb5e-11e9-8552-a5548cc6d203.png)

**Comment by chrismclarke** [comment]
The way things are coded currently, if the page sees there are zero how-tos (just an empty array) it thinks it is still waiting to load (like in the very first load). Ideally there should be a better way to differentiate between not-yet-loaded and loaded-but-no-results. 

As a minimum, simply swapping the behaviour so that zero how-tos a message saying there are none and mis-diagnosing when the how-tos are still loading would be better in case anyone wants to take this on.
