### ISSUE TITLE
[bug] URL in new sign-up email is not from "dev.onearmy.cloud"

### ISSUE THREAD

**Issue by shadiakiki1986** [ONEARMY/community-platform#754]
**Describe the bug**
Not really a bug, but potential concerns :) Upon signing up with a new account, I received an email to confirm my subscription, but the URL is `https://precious-plastic-v4-dev.firebaseapp.com/__/auth/action?mode=verifyEmail&oobCode=...&apiKey=...&lang=en`. First of all, it's not from the domain `onearmy.cloud`. Second, I'm not sure if the `apiKey` is a sensitive info or not. Just thought of giving you guys a heads up about this.

**To Reproduce**

1. Go to 'registration confirmation email'
2. Click on 'link provided'

**Expected behavior**
A URL that starts with `onearmy.world`

**Screenshots**

**Additional context**

**Comment by thisislawatts** [comment]
Thanks for the report @shadiakiki1986.

We are using the default notifications that ship with the Firebase Auth product. These definitely could do with some visual refinement to improve trust signals, but otherwise from a functional perspective these links are behaving as expected. 

Please feel free to re-open this issue if you have any outstanding concerns.
