### ISSUE TITLE
Incorrect contacts/links in Profile

### ISSUE THREAD

**Issue by tmhung88** [ONEARMY/community-platform#762]
**Describe the bug**
All links/contacts were prefixed with http://localhost:3456/u/<link>
![image](https://user-images.githubusercontent.com/2813016/68475816-ba5a9700-025b-11ea-94d2-423bab46f9eb.png)

**To Reproduce**
Open a profile that has contacts & links. Click on any of them and users are taken

**Expected behavior**
- Users should open contacts/links correctly

**Comment by elyeel** [comment]
Hi, I found the issue lies with missing "http://" or "https://" link-prefix. If a user inputs the link incomplete, i.e "www.google.com" will not open the linked website. Instead, the user should input "http://www.google.com" and this should work fine.

Below is the sample when the user hovers on a complete website address.
![test](https://user-images.githubusercontent.com/51432156/68733601-02dfc080-058c-11ea-9671-0a6c0af21b6c.png)

Below is the sample when the user hovers on an incomplete website address.
![test2](https://user-images.githubusercontent.com/51432156/68733778-b052d400-058c-11ea-857a-0218b7771e35.png)

Please Advise

**Comment by BenGamma** [comment]
Yep thanks for pointing out @elyeel. Issue is telated to #526
