### ISSUE TITLE
[bug] can't interact with db on certain browsers.

### ISSUE THREAD

**Issue by BenGamma** [ONEARMY/community-platform#807]
**Describe the bug**
Some users experiences the impossibility to interact with the db. The error in the console is 
Known issue with :
- private browsing window on mozilla 70.0.1, on macOS
- for some users on windows 10 and same version of mozilla ( explained in #801 )
Error is the same in both cases : `uncaught exception: Object`. But when you open the map section, there is a warning in the console : `A mutation operation was attempted on a database that did not allow mutations.` 

**Expected behavior**
Databases should be accessible.

**Additional context**
Seems to be linked with indexedDB, and it's an old bug from mozilla's core. See https://bugzilla.mozilla.org/show_bug.cgi?id=781982

**Comment by chrismclarke** [comment]
Yeah it's a tricky one, I just spent some time looking at and not sure what the best option is. It is due to firefox incognito not supporting indexeddb, as would a handful of legacy browsers and incognito modes (only chrome does support).

There's no immediate way to check if idb will be supported, so instead we would need to rely on attempting to open, checking for error, and then offering some sort of fallback. This is tricky to implement as all the current methods are designed for dbs to be immediately available (defined in constructor methods, so no room for async methods), so will take a bit of refactoring to have some sort of 'ready' method (even if it only takes a couple ms to do).

To make matters worse the latest 'fix' for caching has a built-in behaviour to refresh the page on cache issues, which now will continuously refresh the page on these browsers. Needs more investigation, although I'm downgrading priority as it really is only a fairly small subset of browsers with these issues.

**Comment by davehakkens** [comment]
instead of fixing. could the error message be changed?

> A mutation operation was attempted on a database that did not allow mutations.

Could be something like

> Hmm something went wrong. Probably best to try another browser and avoid incognito

**Comment by chrismclarke** [comment]
> instead of fixing. could the error message be changed?

Nah, found a fix :D
