### ISSUE TITLE
Display mail for admin

### ISSUE THREAD

**Issue by davehakkens** [ONEARMY/community-platform#937]
### Show email in profile for admin
Show the mail address of the user account. (used to create an account) in the profile. Only admin should be able to see this. It makes it easier to get in touch and moderate content

### Page related
User profile: https://community.preciousplastic.com/u/precious-plastic

### Mockup
<img width="568" alt="afbeelding" src="https://user-images.githubusercontent.com/13672737/78389311-d08a3a80-75e2-11ea-94a9-7d44825a2974.png">

**Comment by chrismclarke** [comment]
As the emails aren't stored in the database this will have to work slightly differently, using the backend `firebase-functions` to receive the user_id, retrieve the account email and send back. 

From a frontend I think this would work better as a button to only make the request on demand (it could just be a contact button that opens a mailto link on retrieval), with the button only visible to admins. From the backend this could probably be a firebase callable function, perhaps with added checks for current logged in user permissions. So overall a moderate bit of work to be done.

**Comment by davehakkens** [comment]
ah. Button is also perfectly fine.
But that does sounds like a bit more complex then intended..
hmm..
Maybe keep it open for someone that is very excited to do it?

**Comment by davehakkens** [comment]
And if we leave it as it is in your example, it is ready? Or how does that live example work?

**Comment by chrismclarke** [comment]
Yeah it's ready, the only difference is that instead of showing a text box it opens as a mailto email link. But could easily make it a text box instead. The live example works by:
1. visit the link https://5e975b9c0c93b3000803ed78--oa-preview.netlify.app/
2. log in using your dev site username/pw
3. visit a profile page
4. you should see the button (as you are an admin). Click it to see what happens

I would take a screen capture but it doesn't show the mail client opening as it only records browser window.

**Comment by davehakkens** [comment]
huh. i think i mixed up 2 threads here.
But indeed tested and replied here: https://github.com/ONEARMY/community-platform/pull/944
