### ISSUE TITLE
[feature request] - Ability to change username

### ISSUE THREAD

**Issue by chrismclarke** [ONEARMY/community-platform#992]
**Is your feature request related to a problem? Please describe.**
We've had requests (and requested others) to change their name, particularly in cases where locations used aren't very descriptive (e.g. country level pp-england when operate more locally).

**Describe the solution you'd like**
The username is used to populate the DB so would either need to:
- move to random IDs which can then be used to modify usernames etc. within (previously had but people preferred to be able to see what db entries represented)
- create migration scripts that will copy user info to another db entry, link with auth system to give permissions, migrate any user content such as map pins, howtos etc., and possibly add redirect or some other mechanism if we want to prevent other people also using

**Describe alternatives you've considered**
It might just be easier to have a full profile delete and recreate feature, maybe with some form of data export/import to make things easier and transfer of any linked profile information (e.g. map pins, howtos etc.). Something that would help like this has been proposed as part of #974

Open to ideas/suggestions.

**Comment by alromh87** [comment]
Maybe use a firestore function to trigger a transaction, that way migration would be less prone to errors

**Comment by JanetLaysEggs** [comment]
Hi. I'm interested in helping with this feature request. I'm only a junior software developer "by trade" but I do know my way around migrations etc and like a challenge. I'd love to help on this in anyway. Is there anywhere where we could discuss the current situation in terms of the DB and the backend in general? - I see there is a discord and slack chat? Thanks -J (btw the name is an inside joke among friends ;) )

**Comment by BenGamma** [comment]
Hi J and thanks for your interest !

This issue in particular is a tricky one because it touches the way users logged in and we encountered a few critical bugs  while working on that in the past ( and some still today like #1027), so I don't think this issue is a good one to start with.

That being said there is plenty of issues to work on that are less critical but already super useful. If you like backend stuff there is #984 or #975 for example.

Backend is detailled in multiple sections of [the wiki](https://github.com/ONEARMY/community-platform/wiki/) and yes you can chat in the discord channel #code-community-plateform

**Comment by shenoa** [comment]
@iSCJT I see this issue has been closed. Has some way been provided to change the username? I don't see a feature for it in the live release, and I didn't see any related issues under Community Platform.

**Comment by iSCJT** [comment]
Hi @shenoa, we had a community platform planning meetup last week where we discussed lots of things and reviewed the outstanding issues.  I should have added some context to why I was closing the issue but we were running through a lot together on screen and I forgot to come back to it.  I also should have closed it as something we wouldn't work on.

Because of the way the platform is configured with username === id we decided that this would be a non-trivial and quite time consuming feature to implement for the amount of use it would receive.  For this reason we've decided it's a feature that we won't realistically support and therefore closed it down.
